### ISSUE TITLE
Umi 4 TODOS

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi-next#116]
> 小任务集合，做之前先认领（编辑主贴，加 @自己 ），避免冲突。
## renderer-react

* [x] 用 loadable-components 代替 React.lazy + Suspense @lylwanan https://github.com/umijs/umi-next/pull/202
* [ ] 删除 src\pages\document.ejs ，怎么处理 html 模板 @sorrycc
* [x] hash:true  build 生成的 html 中，引用的还是 ‘/umi.js’ https://github.com/umijs/umi-next/commit/b99b965de5acbb00bee63cea617ac31827c65cc3 @sorrycc 

## plugins
> 注意：1) 全部配置开启 2) 需求描述在对应文件的注释里
* [x] antd @xiaohuoni https://github.com/umijs/umi-next/pull/155
* [x] [antd config] 等 umi Provider 上线，需要重构
* [ ] [antd] 支持一键 externals，配置 `{ antd: { external: true }}` 开启
* [x] dva @sorrycc 
* [x] analytics @YdreamW  https://github.com/umijs/umi-next/pull/206 
* [x] dayjs @YdreamW https://github.com/umijs/umi-next/pull/208
* [x] locale @YdreamW https://github.com/umijs/umi-next/pull/211
* [x] request @YdreamW  https://github.com/umijs/umi-next/pull/219
* [ ] ...

## preset-umi
* [x] 过滤约定路由文件,比如 pages/**/components,修改 api.appData.route @xiaohuoni https://github.com/umijs/umi-next/pull/273
* [x] exports support types (import type all from umi) @xiaohuoni https://github.com/umijs/umi-next/pull/275
* [ ] transform IEAR 处理绝对路径依赖（例如 `@fs/node_modules/antd`）的方案不兼容 windows

## preset-built-in

* [x] umi g page index @xiaohuoni https://github.com/umijs/umi-next/pull/131
* [x]  umi plugin list @siyi98 https://github.com/umijs/umi-next/pull/157
* [x] umi config list @xiaohuoni https://github.com/umijs/umi-next/pull/138
* [x] umi config set alias @xiaohuoni https://github.com/umijs/umi-next/pull/138
* [x] umi config get alias @xiaohuoni https://github.com/umijs/umi-next/pull/138
* [x] umi config remove alias @xiaohuoni https://github.com/umijs/umi-next/pull/138
* [x]  umi config list 默认应该只列用户的配置，umi config list --all 才包含所有的 https://github.com/umijs/umi-next/pull/144
* [x]  umi config remove 和 set 后用 prettier 格式化一下 https://github.com/umijs/umi-next/pull/144
* [x] plugin.ts 变更时自动重启 dev server @siyi98 https://github.com/umijs/umi-next/pull/168
* [x] 约定式的 favicon，自动识别 src/favicon.ico 文件，支持 ico、gif、png、jpg、jpeg、svg、avif、webp 后缀 @xiaohuoni https://github.com/umijs/umi-next/pull/161/
* [x] 扩展 umi g @xiaohuoni https://github.com/umijs/umi-next/pull/159
* [x] npmClient @xiaohuoni https://github.com/umijs/umi-next/pull/163
* [x] require bug，解析用户的配置文件时，未提前将 .js 文件编译成commonjs规范的代码，导致报错 https://github.com/umijs/umi-next/commit/32ad3f00091287361a49e5177aaf01e95790ea19

## create-umi 
* [x] 支持创建项目 @xiaohuoni https://github.com/umijs/umi-next/pull/140
* [x] 支持创建插件 @xiaohuoni  https://github.com/umijs/umi-next/pull/140
* [ ] umi@4 发布之后，调整 templates

## bundler-esbuild
* [x] 支持 alias 配置 @xiaohuoni https://github.com/umijs/umi-next/pull/167
* [x] 支持 externals 配置 @xiaohuoni https://github.com/umijs/umi-next/pull/169
* [x] 支持 less @xiaohuoni https://github.com/umijs/umi-next/pull/170
* [x] alias 支持 $ 结尾 https://webpack.js.org/configuration/resolve/#resolvealias 参考这个 @xiaohuoni https://github.com/umijs/umi-next/pull/171
* [x] 支持 less 中使用 alias @xiaohuoni https://github.com/umijs/umi-next/pull/215
* [x] support svg @xiaohuoni https://github.com/umijs/umi-next/pull/217
* [x] postcss @xiaohuoni https://github.com/umijs/umi-next/pull/220

## bundler-vite
* [x] upgrade svgr to 6 @lylwanan https://github.com/umijs/umi-next/pull/198
* [x] dev 和 build 支持配置 extraBabelPlugins 和 extraBabelPresets 参数 @PeachScript 
* [x] pnpm dev -- --vite 时有大量警告，应该是依赖预编译也走了 babel @PeachScript 
* [x] onCompileDone 和 onDevCompileDone 需要加一个参数 time: number，表示编译时间 @PeachScript https://github.com/umijs/umi-next/pull/142
* [x] vite dev 传入的 middleware 不生效 @PeachScript https://github.com/umijs/umi-next/pull/141
* [x] build 没跑通，会报 `Could not resolve entry module (index.html)` 错误 @PeachScript https://github.com/umijs/umi-next/pull/146
* [x] vite build 的 onBuildComplete 参数不对，需要参考 https://github.com/umijs/umi-next/blob/598a9ee2e6ab08adceeddafa12b0202c4b1d9eeb/packages/preset-built-in/src/types.ts#L28 @PeachScript https://github.com/umijs/umi-next/pull/143
* [x] IE11 兼容 (plugin-legacy) @devilmancbc https://github.com/umijs/umi-next/pull/314
* [x] 热更新 fastRefresh 无法生效（未能复现） @devilmancbc 
* [x] build 报错 `@@/exports` 找不到 @devilmancbc 
* [x] dev server 端口占用不会自动递增 @Yurisa #433 
* [x] 缺少类似 `chainWebpack` 的口子允许用户修改配置 @devilmancbc #428 
* [ ] 兼容 Windows
* [ ] 性能优化点排查

### build
- [x] copy @xiaohuoni  https://github.com/umijs/umi-next/pull/118
- [x] svgr + svgo @xiaohuoni  https://github.com/umijs/umi-next/pull/119
- [x] enable webpack fs cache by default
- [x] swc @xiaohuoni https://github.com/umijs/umi-next/pull/123
- [x] use custom swc-loader support loader js @siyi98 https://github.com/umijs/umi-next/pull/218
- [ ] swc version of umi plugins @Yurisa 
- [x] webpack require hook @xiaohuoni  https://github.com/umijs/umi-next/pull/125
- [x] 支持 esm 格式的输出 @siyi98 https://github.com/umijs/umi-next/pull/172
- [ ] 支持 import 远端的 esm @siyi98 
- [ ] pre bundle css-loader dep
- [x] export not found warning 如果来源是项目代码，报错 @cdllqos
- [x] upgrade svgr to 6 @xiaohuoni https://github.com/umijs/umi-next/pull/195
- [x] use custom @svgr/webpack @xiaohuoni https://github.com/umijs/umi-next/pull/199

### dev
- [x] ws auto recconnect @xiaohuoni  https://github.com/umijs/umi-next/pull/127
- [x] fast refresh @xiaohuoni https://github.com/umijs/umi-next/pull/135
- [ ] pre bundle fast refresh deps
- [x] mock @xiaohuoni https://github.com/umijs/umi-next/pull/186
- [x] proxy @xiaohuoni  https://github.com/umijs/umi-next/pull/128

### chore

* [x] 修复 node 17 下报错的问题
* [x] 一个 example，裸 webpack + `@umijs/mfsu`，让 mfsu 能用于非 umi 体系，https://github.com/sorrycc/example-webpack-mfsu
* [x] publicPath: 'auto' 及 ie 补丁，https://github.com/amiller-gh/currentScript-polyfill @siyi98 https://github.com/umijs/umi-next/pull/191
* [x] 完善 bundler-webpack 的 schema，可参考 umijs/umi 仓库的原有配置，尽量完整和细致 @xiaohuoni  https://github.com/umijs/umi-next/pull/133
  * https://github.com/umijs/umi-next/blob/b42dd2ca35913fe5d618d25fea6d03e2fac63899/packages/bundler-webpack/src/schema.ts#L3
* [x] hmr bug，修改文件两次，第一次不会 hmr，第二次才会 @sorrycc 
* [x] copy-webpack-plugin @xiaohuoni  打包压缩后有 3M，尺寸不正常，怀疑把 webapck 打了一遍 https://github.com/umijs/umi-next/pull/120
* [x] hmr bug，触发 hmr 的时候，会触发页面刷新。导致页面状态丢失。正确逻辑应该是仅重载 hot 文件 @sorrycc
* [x] window path error @CJY0208 https://github.com/umijs/umi-next/pull/180
* [x] mfsu window 兼容？@chenshuai2144 https://github.com/umijs/umi-next/pull/205
* [x] umi cache clean @xiaohuoni

**Comment by sorrycc** [comment]
@fengsx 邀请你了，接受邀请，然后编辑下主贴，任务加加 `@fengsx` 。

**Comment by xiaohp** [comment]
现在能试用 beta 版本么？

**Comment by sorrycc** [comment]
@xiaohp 再等几个 beta 吧，现在功能不太稳定。

**Comment by Yurisa** [comment]
认领一下 swc version of umi plugins 先从auto-css-modules开始吧 @sorrycc

**Comment by TinsFox** [comment]
认领 
- [ ] umi@4 beta 发布之后，调整 templates

**Comment by xiaohuoni** [comment]
@TinsFox 这个还要等其他方案都出了一起调整。（就是等云谦给一个最佳实践的意思）😂

**Comment by lylwanan** [comment]
用 loadable-components 代替 React.lazy + Suspense #201

**Comment by conioX** [comment]
pwa?

**Comment by Gzbox** [comment]
umi 4 rc 现在可以使用了吗？

**Comment by xiaohuoni** [comment]
mac 的可以正常使用，window 的要等下 rc-2

**Comment by kaoding** [comment]
大概，什么，时候，可以，发布？

**Comment by xiaohuoni** [comment]
> 大概，什么，时候，可以，发布？

已经发了
