### ISSUE TITLE
[RFC] React SSR

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi-next#13]
# 【RFC】Umi@3 react SSR

[https://github.com/umijs/umi-next/pull/12](https://github.com/umijs/umi-next/pull/12)

## 特性

- [ ] 开箱即用
- [ ] polyfill 支持
  - [ ] 默认关闭（开启后会使三方库 `isBrowser` 判断失效，带来渲染不一致问题）
- [ ] 服务端无关
- [ ] 支持 CSR 
- [ ] 支持 dynamicImport 路由分割
- [ ] 兼容 html 与 jsx 页面模板（在服务端可定制）
  - [ ] 支持自定义 `document.ejs` 来作为 SSR 模板
  - [ ] 使用 jsx Document 组件定义模板
- [ ] runtime 渲染支持中间件/插件方式，通过配置开启
  - [ ] react-helmet
  - [ ] react-helmet-async
  - [ ] react-document-title
  - [ ] dva
- [ ] 用户 Layout 支持 getInitialProps 
- [ ] preload 支持
- [ ] Document 支持
- [ ] @umijs/plugin-prerender 预渲染插件     
  - [ ] 动态路由是默认 index.html 生成 `[id].html` 文件，走客户端渲染
  - [ ] 支持预览，build 后可以直接 server dist 目录

优化点：

- [ ] 超时处理
- [ ] 支持 Stream 方式渲染
- [ ] 针对服务端渲染的 babel 配置，优化 React Node 服务端 bundle 大小
- [ ] AppShell & PWA 实现
- [ ] 支持 Serverless，直接打出可部署的 server.js

## 改变

相对于 umi@2：

1. [Break Change] `getInitialProps`  中的 `location` 只在 客户端 使用。 
1. 不再使用 [umi-server](https://github.com/umijs/umi-server) ，直接使用 `@umijs/renderer-react` 
1. [@umijs/plugin-prerender](https://github.com/umijs/plugins/blob/master/packages/%40umijs/plugin-prerender) 插件内置进 umi，通过 `prerender` 开启。
1. 出于 runtime 性能问题，server 不再使用 [cheerio](https://www.npmjs.com/package/cheerio)

<a name="t1Iat"></a>
## 用法
<a name="2nK4l"></a>
### SSR 
umi@2 的用法：

```javascript
import server from 'umi-server';

const render = server({
  // get dist/umi.server.js
  root: join(__dirname, 'dist'),
});

http.createServer(async (req, res) => {
   ...
   const ctx = {
     req,
     res,
   }
   const { ssrHtml } = await render(ctx);
  // => <!doctype html><html>...</html>
})
```

在 umi@3 使用： 

基本使用：

```javascript
// .umirc.ts
export default {
  ssr: true,
  routes: [
    { path: '/', component: () => <p>Home</p> },
    { path: '/news', component: () => <p>News</p> },     
  ]
}
```

build 出 `umi.server.js` 

```javascript
// server/index.ts
import { serverRender } from './umi.server';

http.createServer(async (req, res) => {
   ...
   const ctx = {
     req,
     res,
     url: '/',
     renderOpts: {
       // staticMarkup: false,
       // customRender: (element) => string
     }
   }
   const html = await serverRender(ctx);
  // => <!doctype html><html>...</html>
})
```

<a name="jvwbI"></a>
### prerender

umi@2 通过插件的形式：

```javascript
// .umirc.ts
export default {
	ssr: true,
  plugins: [
    ['@umijs/plugin-prerender'] 
  ]
}
```

umi@3 使用形式：

```javascript
// .umirc.ts
export default {
	ssr: true,
  prerender: true,
  // exportStatic 配置直接废弃掉？
  // 还是 ssr + exportStatic 组合起来相当于 prerender
}
```

=> build

```javascript
- dist	
  - index.html
  - news.html
  - news
  - [id].html => 实际是默认的 html 模板，走 CSR
```

### 构建
webpack 构建是走同时构建、还是先构建 client 再构建 server<br />同时构建的好处：速度快，并行构建<br />先后构建：可以拿到 client 端的 manifest ，可以拿到静态资源 hash 名。[replaceChunkMaps.ts#L26-L29](https://github.com/umijs/umi/blob/5e0bca942ce3f98cb522d13dd7728afed4781fa0/packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.ts#L26-L29)

### 路由同构
按官方文档：[react-router/web/guides/server-rendering](https://reacttraining.com/react-router/web/guides/server-rendering)

### getInitialProps 数据预获取

路由配置：

```javascript
{
  routes: [
    { path: '/', component: Layout },
    { path: '/news', component: News },
    { path: '/news/:id', component: NewsDetail },    
  ]
}
```

为了在服务端，让 Layout 和 Page 都能匹配到 `getInitialProps`  值，会将当前 url 匹配到层级路由依次执行 getInitialProps ，同时在客户端注入到 `window.g_initialData`，返回如下数据格式：

```javascript
// 访问 /news/:id
{
  '/': {
    data: 'parent'
  },
  '/news': {
    data: 'news',
  },
  '/news/:id': {
    data: 'newsId',
  }
}
```

渲染出来就是：

```javascript
<div>
  <div>
   parent
   <div>
    news
    <p>newsId</p>
   </div>
  </div>
</div>
```

其中 getInitialProps 在客户端和服务端的传值略微不同，如下：

```ts
export interface IGetInitialProps {
  isServer: boolean;
  match: match;
}

export interface IGetInitialPropsServer extends IGetInitialProps {
  req?: IncomingMessage;
  res?: ServerResponse;
}

export interface IGetInitialPropsClient extends IGetInitialProps {
  location?: Location;
}
```

### SSR 中间件

不同于服务端框架中间件，类似于输出 html 前的预处理操作，使用方式：

```javascript
import { serverRender } from './umi.server';
const DocumentTitle = require('react-document-title');

http.createServer(async (req, res) => {
   ...
   const ctx = {
     req,
     res,
     url: '/',
     renderOpts: {
       postProcessHtml: [
        // 支持 react-document-title
        (html) => {
           const title = DocumentTitle.rewind();
           if (title) {
             return html.replace(/<title>.*?<\/title>/, title);
	         }
           return html;
          },
          ...
        ]
     }
   }
   const html = await serverRender(ctx);
  // => <!doctype html><html>...</html>
})
```

compose 实现：

```javascript
import { Handler } from './index';

/**
 * render html handlers pipe
 * const resultHtml = compose(
 *   handler1,
 *   handler2,
 *   hanlder3,
 *   ...
 * )($, args);
 *
 * @param handler ($, args) => $
 */
const compose: (...handler: Handler[]) => Handler = (...handler) =>
  handler.reduce((acc, curr) => ($, args) => curr(acc($, args) || $, args) || $);

export default compose;
```

### dva 支持

和之前保持一致，通过 @umijs/plugin-dva 插件实现。

### Layout 模板

因为 `document.ejs` + `scripts` + `metas` + `links` 已经可以定制各种 html 模板，SSR 直接用 `getHtmlGenerator` 拿到模板，

如果是 服务端注入 script，还是可以通过 [中间件](#中间件) 来完成。

### 动态加载

在服务端时直接渲染成 `require`，不再走 dynamicImport 方式，对服务端基本没有影响。

## 参考

<a name="rOSWB"></a>
### Next.js
[https://github.com/zeit/next.js](https://github.com/zeit/next.js)

<a name="4SuB5"></a>
### egg-react-ssr
[https://github.com/ykfe/egg-react-ssr](https://github.com/ykfe/egg-react-ssr)

<a name="REdz4"></a>
### after.js
[https://github.com/jaredpalmer/after.js](https://github.com/jaredpalmer/after.js)

<a name="NUYGf"></a>
### razzle
[https://github.com/jaredpalmer/razzle](https://github.com/jaredpalmer/razzle)

**Comment by xiexingen** [comment]
这个什么时候开始支持
