### ISSUE TITLE
history和single-spa冲突，单一回调会重复执行两次，导致umi和qiankun一起使用时行为异常

### ISSUE THREAD

**Issue by shengbeiniao** [umijs/umi-next#15]
## What happens?
![image](https://user-images.githubusercontent.com/3301995/72416996-db3aed80-37b2-11ea-8ede-cd6066547775.png)

## 最小可复现仓库

 [History代码库错误行](https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createBrowserHistory.js#L267) 

[Single-SPA代码库错误行](https://github.com/CanopyTax/single-spa/blob/92efd71ace891d59eb1005d09dd5cf532fbba154/src/navigation/navigation-events.js#L100)

### 错误分析
single-spa改写了window.history.pushState方法，在每次pushState的时候会主动dispatch一个popState事件，被history checkDomListeners捕获，这样通过history.listen注册的监听函数都会被执行两次，如
[connected-react-router handleLocationChange方法](https://github.com/supasate/connected-react-router/blob/7af0ed011d6c1bbdfac822c951d68f750e8bada8/src/ConnectedRouter.js#L53)

### 解决方案
> 尝试自己写插件解决无效
```
# 插件代码
const fs = require('fs')
const path = require('path')

export default function(api, options) {
  api.modifyEntryHistory(memo => {
    const content = fs.readFileSync(path.resolve(__dirname, 'historyPatch.js'), {
      encoding: 'utf8'
    })
    return content
  })
}

# historyPatch.js
/**
 * fix history & single-spa bug, remove checkDOMListeners
 * https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createBrowserHistory.js#L267
 * https://github.com/CanopyTax/single-spa/blob/92efd71ace891d59eb1005d09dd5cf532fbba154/src/navigation/navigation-events.js#L100
 */

require('@zstack/history').createBrowserHistory({ basename: window.routerBase })
```
运行后.umi/history生成如下

```
// create history
const history
/**
 * fix history & single-spa bug, remove checkDOMListeners
 * https://github.com/ReactTraining/history/blob/3f69f9e07b0a739419704cffc3b3563133281548/modules/createBrowserHistory.js#L267
 * https://github.com/CanopyTax/single-spa/blob/92efd71ace891d59eb1005d09dd5cf532fbba154/src/navigation/navigation-events.js#L100
 */ = require('@zstack/history').createBrowserHistory({
  basename: window.routerBase,
});
export default history;

```

但实际运行时，检查sourcemap，系统仍然选用umi-history，怀疑和alias有关

执行npx umi inspect > dev.log
有如下配置
```
history: '/Users/shengbeiniao/zstack/projects/cmp/node_modules/umi-history',
```
重写alias，无法覆盖

- **Umi 版本**：umi@2.12.4 umi-history@0.1.2 single-spa@4.4.2
- **Node 版本**：
- **操作系统**：

**Comment by ycjcl868** [comment]
写错地方了

**Comment by ycjcl868** [comment]
换到 umijs/umi

**Comment by xiaohuoni** [comment]
没写错，写这里，怕被遗忘

**Comment by shengbeiniao** [comment]
解决方案：https://github.com/umijs/umi/issues/3919
