### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by robert-zaremba** [umijs/umi-next#231]
After running `umi dev`, one of the UI libraries wants to use the `global` variable (as window):

```
WS = typeof global.WebSocket !== "undefined" ? global.WebSocket : require_browser();
```

How can I enable `global` through umi webpack?

**Comment by sorrycc** [comment]
umi@4 or umi@3?

**Comment by robert-zaremba** [comment]
umi@4

**Comment by sorrycc** [comment]
show me your umi config.

**Comment by xiaohuoni** [comment]
How to reproduce？
```
console.log(global)
const WS = typeof global.WebSocket !== "undefined" ? global.WebSocket : null;
console.log(WS)
```
![image](https://user-images.githubusercontent.com/11746742/147737763-8b06c914-d450-45a2-a1ba-d0302cfa83f9.png)

**Comment by robert-zaremba** [comment]
> show me your umi config.

This is my config:
```
export default {
	chainWebpack(memo: any, { webpack }) {
		memo;
	},

	headScripts: [`console.log('head script')`],
	scripts: [`console.log('script')`],
	npmClient: 'pnpm',
	svgr: {},
};
```

**Comment by robert-zaremba** [comment]
@xiaohuoni  to reproduce try:
```
global.WebSocket // fails, because global is undefined
globalThis.WebSocket // works
```

One of the libraries uses `global.WebSocket` , so to make it working I added the following hack in `src/app.tsx`:
```
window.global = globalThis;
```

@sorrycc  - I think this is related to webpack config. Could you reopen this issue?
