### ISSUE TITLE
The mfsu version of 4.0.0-beta.16 does not work properly

### ISSUE THREAD

**Issue by jinbaojia** [umijs/umi-next#300]
➜  example-webpack-mfsu git:(master) ✗ pnpm dev    

> @ dev /Users/xxx/self-project/example-webpack-mfsu
> webpack-dev-server

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8082/
<i> [webpack-dev-server] On Your Network (IPv4): http://11.37.60.200:8082/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8082/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/xxx/self-project/example-webpack-mfsu/public' directory
ERROR in ./src/App.tsx 1:0-29
Module not found: Error: Can't resolve 'mf/react' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/antd.tsx 1:0-31
Module not found: Error: Can't resolve 'mf/antd/dist/antd.css' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/App.tsx 2:0-26 5:88-92
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/antd.tsx 2:0-39
Module not found: Error: Can't resolve 'mf/antd/es/button' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/App.tsx 2:0-26 5:88-92
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/antd.tsx 3:0-48
Module not found: Error: Can't resolve 'mf/antd/es/date-picker' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/App.tsx 2:0-26 5:88-92
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/antd.tsx 4:0-37
Module not found: Error: Can't resolve 'mf/antd/es/input' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/App.tsx 2:0-26 5:88-92
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/antd.tsx 5:0-29
Module not found: Error: Can't resolve 'mf/react' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/App.tsx 2:0-26 5:88-92
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/framer-motion.tsx 13:0-51
Module not found: Error: Can't resolve 'mf/framer-motion' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/App.tsx 3:0-43 5:134-146
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/framer-motion.tsx 14:0-29
Module not found: Error: Can't resolve 'mf/react' in '/Users/xxx/self-project/example-webpack-mfsu/src'
 @ ./src/App.tsx 3:0-43 5:134-146
 @ ./src/main.tsx 3:0-24 4:50-53

ERROR in ./src/main.tsx 1:0-29
Module not found: Error: Can't resolve 'mf/react' in '/Users/xxx/self-project/example-webpack-mfsu/src'

ERROR in ./src/main.tsx 2:0-36
Module not found: Error: Can't resolve 'mf/react-dom' in '/Users/xxx/self-project/example-webpack-mfsu/src'

10 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.64.4 compiled with 10 errors in 1045 ms

**Comment by fz6m** [comment]
you should use `4.0.0-beta.9`, because `4.0.0-beta.16` and `4.0.0-beta.9` are configured differently
