### ISSUE TITLE
Problem with vite scan + externals

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi-next#323]
复现步骤，

```bash
$ cd examples/boilerplate
$ npm run dev -- --vite
```

**Comment by PeachScript** [comment]
vite issue 还在[讨论 externals 怎么解](https://github.com/vitejs/vite/issues/3001)，所以之前没有实现、先记 [TODO](https://github.com/umijs/umi-next/blob/master/packages/bundler-vite/src/config/transformer/rollup.ts#L22) 了，目前比较倾向于这个解法 https://github.com/vitejs/vite/issues/3001#issuecomment-836352935

**Comment by PeachScript** [comment]
看了下 ice 的实现挺简洁、也更 Webpack，准备采用这个方案了：https://github.com/alibaba/ice/blob/8c9a2ad36d4b68af67fe5fe419293e306249a60a/packages/vite-service/src/plugins/external.ts#L13
