### ISSUE TITLE
umi4中如何获取route字段

### ISSUE THREAD

**Issue by cl1107** [umijs/umi-next#327]
![image](https://user-images.githubusercontent.com/21985353/151362330-02fb4a1f-87b1-4ad0-8371-7b3e59f78c8d.png)
umi4中props默认获取到的是{},那需要从哪里获取到图中的route呢？

**Comment by cl1107** [comment]
仓库里找了一下比较接近的是 useAppData 这个hook返回的值

**Comment by xiaohuoni** [comment]
```
import { useAppData } from 'umi';
const { clientRoutes } = useAppData();
```
