### ISSUE TITLE
使用umipro的时候，vscode提示 “找不到模块“umi”或其相应的类型声明”

### ISSUE THREAD

**Issue by cl1107** [umijs/umi-next#328]
![image](https://user-images.githubusercontent.com/21985353/151371261-86e073ec-f0f4-44d5-bbd3-e3fca7edb9b9.png)
安装的依赖如下图所示：
![image](https://user-images.githubusercontent.com/21985353/151371299-b5de066a-416b-4cdf-bf53-fe8385b10473.png)
![image](https://user-images.githubusercontent.com/21985353/151373302-905c17dc-fc2d-4557-b89f-a4e7764ad2f3.png)

同时也安装umi后，才不会提示找不到模块umi，但是输入后方法后，vscode导入的自动提示就会有两条
![image](https://user-images.githubusercontent.com/21985353/151372829-475a04aa-0aab-4532-ba0f-c47d00ccc19d.png)
![image](https://user-images.githubusercontent.com/21985353/151373231-0d312b39-d094-4548-b670-65bbf7ec6ae9.png)

**Comment by xiaohuoni** [comment]
import all from '@umijs/pro' ?
