### ISSUE TITLE
[补充中] Umi UI 迁移 umi@3 记录

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi-next#33]
补充到 https://github.com/umijs/umi-next/wiki/umi-2.0-plugin-migrate-to-umi-3.0

### 插件层

1、`api.config` 注册阶段为 `null`，如果需要在注册阶段获取，使用 `api.service.userConfig`

```diff
export default (api) => {
-   console.log(api.config) // => { ... }
+  console.log(api.config) // => null
}
```

2、`api.chainWebpackConfig` 缺失，目前用的 `api.modifyBundleConfig` ：

```js
// umi 2.x
api.chainWebpackConfig(config => {
  config
    .plugin("umi-ui-compile-status")
    .use(require("./CompileStatusWebpackPlugin").default);
});

// umi 3.x
api.modifyBundleConfig((bundleConfig, { env, bundler: { id } }) => {
  if (env === 'production' && id === 'webpack') {
    const UiCompileStatusPlugin = require("./CompileStatusWebpackPlugin").default;
    bundleConfig.plugins?.unshift(new UiCompileStatusPlugin());
  }
  return bundleConfig;
});
```

3、api 目前缺失

- 路由相关`api.getRoutes` 、`api.getRouteComponents`
- `api.relativeToTmp`
- `api.runCommand`

4、`api` 注册方法异步化、对象化

```js
// before
export default (api) => {
  api.registerCommand('build', {}, (args) => {
    api.applyPlugins('addBar', {
        ...
    })
  })
}

// after
export default (api) => {
  api.registerCommand({
    name: 'build',
    fn: async ({ args }) => {
      await api.applyPlugins({
        key: 'addBar',
        // 必填
        type: api.ApplyPluginsType.add,
        ...
      })
    }
  })
}
```

5. `api.winPath` 、`api.log` 、`api._` 、`api.debug` 等工具类 API 从 `@umijs/utils` 中引入

```js
// before
export default (api) => {
  const { _, log, debug, winPath } = api;
}

// after
import { 
  lodash as _, 
  signale as log,
  createDebug as debug,
  winPath, 
} from '@umijs/utils';

export default (api) => {
  
}
```

6. `api.addEntryCode` 入参由 `string` 改成 `() ⇒ string`

```js
// before
export default (api) => {
  api.addEntryCode(`console.log('foo');`)
}

// after
export default (api) => {
  api.addEntryCode(() => `console.log('foo');`)
}
```

7. 单数变复数，例如 `api.registerPlugin` => `api.registerPlugins`， `api.addHTMLStyles`、`api.addHTMLHeadScripts`、`api.addHTMLScripts`、`api.addHTMLMetas`、`api.addHTMLLinks` 等

### 应用层

- 配置变更
    - `uglifyJSOptions` 配置废弃，改用 `terserOptions`
    - `cssLoaderOptions` ⇒ `cssLoader`
    - `lessLoaderOptions` ⇒ `lessLoader`，css-loader 升级至 `3.x`，配置有 BreakChange，[详见](https://github.com/webpack-contrib/css-loader/blob/229d36a289bcddcba9c35a7078ff5de9226e8c8d/CHANGELOG.md#300-2019-06-11)
    - `output.publicPath` 变更
    - `.env` 环境变量读取缺失
    - `treeShaking` 默认开启，无须配置
- 缺少
    - `chainWebpack`
    - `headScripts` 、`links` 、`scripts` ，计划配置内置，平铺  https://github.com/umijs/umi-next/pull/32

- 代码层
history 导出

```diff
- import history from '@tmp/history';
+ import { history }  from 'umi';
```

`umi/prompt` 缺少（次优先级）

运行时 `app.ts`:

```diff
- export const patchRoutes = (routes) => {}
+ export const patchRoutes = ({ routes }) => {}
```

**Comment by sorrycc** [comment]
`api.chainWebpackConfig` 还是会提供的，我加下。

**Comment by ycjcl868** [comment]
`chainWebpack` 应用层配置也要提供吗？

**Comment by sorrycc** [comment]
提供的。

**Comment by sorrycc** [comment]
treeShaking 默认开启了，无需提供。
