### ISSUE TITLE
example中mfsu-independent 例子启动报错

### ISSUE THREAD

**Issue by AlbertLin0923** [umijs/umi-next#330]
ERROR in ./mfsu-virtual-entry/default.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\XXX\Desktop\work\umi-next\examples\mfsu-independent\mfsu-virtual-entry\default.js: Bad character escape sequence. (1:43)

> 1 | await import('C:\Users\XXX\Desktop\work\umi-next\examples\mfsu-independent\src\index.tsx');

**Comment by sorrycc** [comment]
win path 问题，修复了，等 rc.2 发布。
