### ISSUE TITLE
config文件后缀名导致无法使用esm及msfu的cache文件夹生成的位置不对

### ISSUE THREAD

**Issue by williamnie** [umijs/umi-next#338]
electron环境中会遇到如下两个问题：
1. 不支持esm,
2. msfu的cache文件夹生成的位置不对
复现地址：https://github.com/williamnie/umi3.0-electron/tree/umi4.0

第一个问题将config/config.js改成config.ts 就好了，无法界定是否是bug，建议支持js扩展名
第二个问题是因为electron的特殊环境吧，希望能生成到最外层的node_modules内

**Comment by sorrycc** [comment]
cache 文件夹生成的位置不对会导致啥问题？请求时找不到？

**Comment by williamnie** [comment]
> 

能正常找到，src内应该都是业务代码，再有node_module,比较杂乱

**Comment by sorrycc** [comment]
问题 1 修复了，问题 2 通过 mfsu: { cacheDirectory } 的方式自定义。

**Comment by williamnie** [comment]
> 问题 1 修复了，问题 2 通过 mfsu: { cacheDirectory } 的方式自定义。

问题1大概是哪里的问题呢？
