### ISSUE TITLE
babel-plugin-transform-runtime配置问题

### ISSUE THREAD

**Issue by hasnum-stack** [umijs/umi-next#340]
在使用 babel-plugin-transform-runtime时 , 是否考虑对 [corejs配置](https://www.babeljs.cn/docs/babel-plugin-transform-runtime#corejs)的支持,[目的](https://www.babeljs.cn/docs/babel-plugin-transform-runtime#core-js-aliasing),代价上可能需要再依赖 @babel/runtime-corejs2与@babel/runtime-corejs3

**Comment by sorrycc** [comment]
我理解 map、set、promise 等通过 polyfill 的方式已加上，无需再配这个。
