### ISSUE TITLE
配置路由导致渲染多个layout

### ISSUE THREAD

**Issue by williamnie** [umijs/umi-next#344]
![image](https://user-images.githubusercontent.com/26871884/152936500-f7c7c801-2991-4d26-95dd-28196fc9e1cf.png)
```
 routes: [
    {
      path: '/',
      component: '../layouts/index',
      routes: [{ path: '/', component: 'Index' }],
    },
  ],
```
配置路由时，如果指定了layout （component: '../layouts/index'） 则会渲染出两个layout

**Comment by sorrycc** [comment]
layouts/index 自动加的，无需手动配。

**Comment by williamnie** [comment]
> 

如果想使用其他的layout呢？需要在index里根据pathname自己判断么？

**Comment by sorrycc** [comment]
换个名，不要用 layout/index，然后走配置。

**Comment by williamnie** [comment]
>

**Comment by superlbr** [comment]
`@umijs/pro": "^4.0.0-rc.3` layout没有自动加载
