### ISSUE TITLE
umi引入了esbuild

### ISSUE THREAD

**Issue by 1247748612** [umijs/umi-next#347]
在浏览器中执行esbuild代码报错，看调用栈发现是引入了esbuild代码？

![image](https://user-images.githubusercontent.com/29533304/153023826-ed752ced-7705-42f4-bc02-169794979a6f.png)

使用bundler-vite dev运行

**Comment by sorrycc** [comment]
复现步骤？

**Comment by 1247748612** [comment]
需等这个 https://github.com/umijs/umi-next/pull/346  修复了，我再看看能不能在bundler-vite-demo中复现出来

**Comment by fz6m** [comment]
> 需等这个 #346 修复了，我再看看能不能在bundler-vite-demo中复现出来

直接改 `node_modules` 的代码，本地调试下试试？

**Comment by 1247748612** [comment]
> 直接改 `node_modules` 的代码，本地调试下试试？

调试曲折的很

**Comment by 1247748612** [comment]
### 在bundler-vite-demo中复现成功
![image](https://user-images.githubusercontent.com/29533304/153148346-4d86b38c-cf1b-4547-94ea-a233770ae1fc.png)

### 问题描述

1. 直接修改node_modules中的umi/packages.json代码删掉module后vite不再报错
2. 此时我无论从umi导入任何模块或函数都报syntax error
![image](https://user-images.githubusercontent.com/29533304/153151122-1b931a61-677b-4b3d-8d46-0520e6a2b397.png)
3. 问题出现在umi是个commonjs libary且vite没有针对umi做依赖于构建导致语法错误
4. 尝试在config添加optimizeDeps.include 添加umi模块但不生效
5. 在packages\bundler-vite\src\config\transformer\optimizeDeps.ts 添加如下代码后生效
```typescript
config.optimizeDeps!.include =  (config.optimizeDeps!.include || []).concat([
  "umi"
])
```
6. 重新编译项目
7. 启动项目后复现

### 复现步骤

1. 在`packages\bundler-vite\src\config\transformer\optimizeDeps.ts` 添加如下代码
```typescript
config.optimizeDeps!.include =  (config.optimizeDeps!.include || []).concat([
  "umi"
])
```
2. 执行 `pnpm run build` 重新build
3. 在 `examples\bundler-vite-demo\src\index.tsx` 添加如下代码
```typescript
import { defineConfig } from 'umi';
console.log('defineConfig: ', defineConfig);
```
3. 执行 `pnpm run --filter ./examples/bundler-vite-demo start`

4. 在浏览器console中查看错误

**Comment by fz6m** [comment]
windows 的路径问题吧 - -

**Comment by 1247748612** [comment]
> windows 的路径问题吧 - -

无关系统

vite只针对包含node_modules的地址做预构建，在pnpm workspace 环境下，umi应该是一个软链接，不在node_modules中而在`umi-next\packages\umi\dist`中所以导致无法针对umi做预构建，只能指定include才能成功

**Comment by 1247748612** [comment]
当我注释这行代码
![image](https://user-images.githubusercontent.com/29533304/153334755-60c739c8-816a-4d4c-8bd7-cc6515ea13ac.png)

vite会自从 **/*.html 找需要预处理的依赖，它找到了esbuild。当我删除引用umi的代码，esbuild则不再预构建了，这应该可以证明esbuild被引入在了

**use umi**
![image](https://user-images.githubusercontent.com/29533304/153334839-69b9d4ae-0207-4cb3-a979-3264d8916ee8.png)

**not used**
![image](https://user-images.githubusercontent.com/29533304/153335214-f340ce48-4a7f-44b3-b0b9-396122ddc30c.png)

**Comment by PeachScript** [comment]
先理一下关系，Umi 是应用框架，bundler-vite 是打包器，bundler-vite-demo 是验证打包器的示例项目。

所以，在打包器示例项目中引入应用框架不是正确用法，就像我们不能在 webpack 项目里直接 `import from 'umi'` 一样。

要验证这个问题，得换成 Umi 或者 Umi Pro 的示例项目，比如 `examples/bigfish`、`examples/ant-design-pro`，目前测试下来是可以 work 的。

**Comment by 1247748612** [comment]
work fine

**Comment by aadog** [comment]
问题是咋用vite呢
umi dev --vite 用得还是mfsu啊，
