### ISSUE TITLE
尝试迁移umi 与 bundler-vite相关问题

### ISSUE THREAD

**Issue by Dunqing** [umijs/umi-next#350]
### 尝试迁移使用bundler-vite启动项目

1. 配置文件应与umi的配置文件保持一致，现只支持在config.ts而不支持config/config.ts，.umirc 等
2. bundler-vite的入口文件是src/index.tsx 而 umi 则是 app.tsx，应该彼此兼容
3. 关于alias应该和vite保持一致，如这种`Array<{ find: string | RegExp, replacement: string }>`类型无法支持
4. config中配置modifyViteConfig不生效，从源码中发现目前好像只支持在插件中使用modifyViteConfig更改vite config？（很需要）
5. umi/packages.json 的module路径不存在导致vite找不到入口文件

### 尝试迁移使用umi@next `umi dev --vite`启动项目

1. tmpFiles写入的文件没有针对windows做处理 
2. tmpFiles使用了这个库@umi/renderer-react，但引用的地址为绝对地址且这个库使用了基于commonjs的(如 `hoist-non-react-statics`)库， 导致vite不能将commonjs转为esm然后报错
3. 开发环境引入了polyfill，且这些polyfill基于commonjs导致线上报错

### 性能问题

vite模式启动，性能相当之慢。一直在更新dependencies

**Comment by 1247748612** [comment]
bundler-vite 启动端口已被占用无报错提醒

**Comment by PeachScript** [comment]
使用 `umi dev --vite` 是正确用法，bundler-vite/bundler-webpack 只是解耦的打包器、方便维护或用于其他框架集成，不建议直接在项目中使用、且必然会有和 Umi 层用法不一致的地方。

提到的其他问题：

> 关于alias应该和vite保持一致

Umi 的配置要同时支持 webpack 和 vite，在评估 webpack 适配可行性后会考虑开放正则

> config中配置modifyViteConfig不生效

目前没有这个配置项，讨论好后会新增一个配置，PR 里我们有讨论

> umi/packages.json 的module路径不存在导致vite找不到入口文件

这点你提 PR 修复了，但在 bundler-vite-demo 里引入 umi 验证是不合适的：https://github.com/umijs/umi-next/issues/347#issuecomment-1038800763

> tmpFiles写入的文件没有针对windows做处理

已知 bug，还没想好解决方案，可以帮忙看看，关键点在于 @fs 别名转绝对路径没有好的方案，分支在这里：https://github.com/umijs/umi-next/tree/hotfix/transform-iear-win

> tmpFiles使用了这个库@umi/renderer-react，但引用的地址为绝对地址且这个库使用了基于commonjs的(如 hoist-non-react-statics)库， 导致vite不能将commonjs转为esm然后报错
> 开发环境引入了polyfill，且这些polyfill基于commonjs导致线上报错

这两个问题 macOS 下没有复现，可以提供下复现步骤

> vite模式启动，性能相当之慢。一直在更新dependencies

我们测试下来的确与 webpack 模式没有明显差距，但也不算慢，如果对 vite 比较有经验，可以一起排查下原因

> bundler-vite 启动端口已被占用无报错提醒

已知 bug，会在 Umi 层解

**Comment by 1247748612** [comment]
> vite模式启动，性能相当之慢。一直在更新dependencies
> 我们测试下来的确与 webpack 模式没有明显差距，但也不算慢，如果对 vite 比较有经验，可以一起排查下原因

没细看更新了什么dependencies，感觉把整个项目使用到的库都添加了，似乎与bunder-vite无关

这个pr可能可以解决 https://github.com/vitejs/vite/pull/6758#issue-1124161573

**Comment by 1247748612** [comment]
> 已知 bug，还没想好解决方案，可以帮忙看看，关键点在于 https://github.com/fs 别名转绝对路径没有好的方案，分支在这里：https://github.com/umijs/umi-next/tree/hotfix/transform-iear-win

正则表达式处理太多edge cases了

`@fs` 可以用optimizeDeps.include 解决

![image](https://user-images.githubusercontent.com/29533304/153854976-feb10575-5c90-449e-9ac0-bbddbffb092a.png)

或许这两个可以结合起来？

**Comment by PeachScript** [comment]
esbuild + es-module-lexer + sourcemap 应该是可行的，后续可以替换掉正则方案，但现在问题不在正则匹配上。

`@fs` 前缀是为了让 vite 把绝对路径的文件当做依赖做预编译（相关逻辑：https://github.com/vitejs/vite/blob/main/packages/vite/src/node/optimizer/scan.ts#L327 ），`alias: { '@fs': '/' }` 在 *nix 下可以顺利解析 `@fs/path/to/file` 成 `/path/to/file`，但 win 下没办法解析 `@fs/C:/path/to/file` 成 `C:/path/to/file`，这个是 win 下编译失败的原因。

**Comment by 1247748612** [comment]
### vite

- build时未对entry（/umi.ts）判断做windows支持
- build产物 index.html引入umi.js路径不对

**Comment by 1247748612** [comment]
### vite build

**entry 指定的html 是相对地址，在windows是../../C:/Users/xxxx，使用绝对地址就可以了，如果使用的是相对地址，则转成绝对地址**
https://github.com/umijs/umi-next/blob/35e974ac752b1466df37474c6ec0ee66bd4c816a/packages/bundler-vite/src/build.ts#L61

**build指定的html会被打包至 examples\boilerplate\dist\.umi-production\.bundler-vite-entry\umi.html**
![image](https://user-images.githubusercontent.com/29533304/154426169-e2b8d9aa-e799-4198-a346-d270c89e90fb.png)

**走vite会自行生成html文件，但umi自行生成了一个html文件，不确定是不是想完全自己构建一个index.html** 
https://github.com/umijs/umi-next/blob/3791fad8f1088c9eebb1d886281e27609c91eea4/packages/preset-umi/src/commands/build.ts#L155-L161

**Comment by PeachScript** [comment]
端口占用检测和支持覆盖 Vite 配置在最新的 RC 里已支持：https://github.com/umijs/umi-next/releases/tag/v4.0.0-rc.6

**Comment by aadog** [comment]
问题是咋用vite呢
umi dev --vite 用得还是mfsu啊，咋用request这些呢

**Comment by xierenyuan** [comment]
> 问题是咋用vite呢 umi dev --vite 用得还是mfsu啊，咋用request这些呢

config 增加`vite: {}` 开启vite 模式. `request` 插件在 `@umijs/plugins` 包中 可以直接使用 `@umijs/max`

**Comment by sorrycc** [comment]
有问题再 reopen。
