### ISSUE TITLE
Question: 为何plugin 引入模块都使用的绝对地址

### ISSUE THREAD

**Issue by 1247748612** [umijs/umi-next#367]
这是因为什么限制的？貌似这种写法如果使用方也有同一个模块，是会导致引用的不是同一个？

**Comment by sorrycc** [comment]
plugin 的依赖是 plugin 的依赖，不是项目的，plugin 生成的临时文件是到项目的，项目去引 plugin 的依赖就有风险，可能引到也可能引不到。

**Comment by 1247748612** [comment]
> plugin 的依赖是 plugin 的依赖，不是项目的，plugin 生成的临时文件是在项目里，然后项目去引 plugin 的依赖就有风险，可能引到也可能引不到。

如果plugin是和umi3一样独立的包，为每个plugin使用的libary都添加到peerDependencies中是不会不存在的

目前的plugin有大量的在使用winPath，在写插件时一不留意就不兼容windows了。

这样做的好处有很多
- 插件中不再需要windows支持
- 可以解决vite相关的问题 https://github.com/umijs/umi-next/issues/350#issuecomment-1039783810
- 类型也会更加友好
- ...

**Comment by 1247748612** [comment]
目前按照我这种方式，改了源码，总算是吧ant-design-pro跑起来了


system plathom: windows 11

![image](https://user-images.githubusercontent.com/29533304/154197964-b34ffaa6-abab-4f38-8a31-871db68cec5c.png)

**Comment by 1247748612** [comment]
测试项目：examples/boilerplate
测试环境: windows + vite | windows + webpack

### dev
缺少一些依赖，成功运行
![image](https://user-images.githubusercontent.com/29533304/154205650-c716f9b5-5ace-4619-b353-ef7ca2ca645f.png)


### build
部分配置没兼容windows, 成功打包，代码运行成功
![image](https://user-images.githubusercontent.com/29533304/154207135-42926d75-e19b-4c1b-9248-9cf8bd1eba6b.png)

**Comment by 1247748612** [comment]
@PeachScript  cc
