### ISSUE TITLE
不能禁用 @umijs/plugin-layout ？

### ISSUE THREAD

**Issue by zhengshuai1001** [umijs/umi-next#370]
注释 layout 配置项
![Snipaste_2022-02-16_19-01-20](https://user-images.githubusercontent.com/9513530/154251442-91af377c-ec4d-4c6f-b4ec-e79fe06774e3.png)
页面报错
![Snipaste_2022-02-16_19-02-58](https://user-images.githubusercontent.com/9513530/154251587-5f056e8a-8f3b-45c0-b5b6-c776616a9646.png)

不想用 antd 的菜单，可以禁用 layout 吗？

**Comment by sorrycc** [comment]
通过 `layout: false` 禁用，现在的版本在 windows 下有路径问题，已修复，等这周的 rc.2 发布吧。
