### ISSUE TITLE
[Feature Request] 能否支持上类似后端的可插拔模块化形式

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi-next#38]
## Background

比如一个系统由N个模块组成，这些模块不能单独部署，但是可以在系统中任意组合(每个模块包含单独的路由、model等)最后在应用中将每个模块里面的路由加载进来

**Comment by ycjcl868** [comment]
现在就是的吧

**Comment by iShawnWang** [comment]
@xiexingen 你找的应该是这个 : 微前端插件 https://github.com/umijs/umi-plugin-qiankun

**Comment by xiexingen** [comment]
> @xiexingen 你找的应该是这个 : 微前端插件 https://github.com/umijs/umi-plugin-qiankun

还不是这种，举个例子 
现在有n个模块系统 @xxg/blogs   @xxg/account .... 这些模块系统自带了路由、页面这些
然后这些模块系统可以被安装到应用中  安装了blogs模块系统就有这块的功能和菜单
类似这样的
