### ISSUE TITLE
mfsu没法和antd 3.x版本一起使用，为什么这两个会冲突

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi-next#386]
![image](https://user-images.githubusercontent.com/37628562/155272893-ff5dc136-f466-4c44-b786-a88942671ab3.png)
antd 版本3.5.22
mf-va_remoteEntry.js:59946 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at mf-va_remoteEntry.js:59946:54
    at Array.forEach (<anonymous>)
    at Function.add (mf-va_remoteEntry.js:59945:19)
    at node_modules/antd/es/icon/index.js (mf-va_remoteEntry.js:60206:24)
    at __init (mf-va_remoteEntry.js:17:58)
    at node_modules/antd/es/input/Input.js (mf-va_remoteEntry.js:60403:7)
    at __init (mf-va_remoteEntry.js:17:58)
    at node_modules/antd/es/input/index.js (mf-va_remoteEntry.js:62102:7)
    at __init (mf-va_remoteEntry.js:17:58)
    at node_modules/antd/es/auto-complete/index.js (mf-va_remoteEntry.js:62471:7)
    at __init (mf-va_remoteEntry.js:17:58)
    at node_modules/antd/es/index.js (mf-va_remoteEntry.js:144531:7)
    at __init (mf-va_remoteEntry.js:17:58)
    at node_modules/.cache/mfsu/mf-va_antd.js (mf-va_remoteEntry.js:144668:7)
    at __init (mf-va_remoteEntry.js:17:58)
    at mf-va_remoteEntry.js:146074:43

@sorrycc

**Comment by sorrycc** [comment]
给个复现仓库。

**Comment by yaodong5063** [comment]
> 

examples 文件下 boilerplate文件
package.json文件修改为
{
  "scripts": {
    "build": "umi build",
    "dev": "umi dev",
    "start": "npm run dev"
  },
  "dependencies": {
    "umi": "4.0.0-rc.2",
    "antd": "3.22.2"
  }
}

pages文件夹下面的index.tsx改为

// @ts-ignore
import marked from 'marked';
import React from 'react';
// @ts-ignore
import Smileurl, { ReactComponent as SvgSmile } from '../smile.svg';
import './global.less';
// @ts-ignore
import styles from './index.less';
import { Table, Divider, Tag,Card } from 'antd';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
    render: text => <a>{text}</a>,
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
    key: 'address',
  },
  {
    title: 'Tags',
    key: 'tags',
    dataIndex: 'tags',
    render: tags => (
      <span>
        {tags.map(tag => {
          let color = tag.length > 5 ? 'geekblue' : 'green';
          if (tag === 'loser') {
            color = 'volcano';
          }
          return (
            <Tag color={color} key={tag}>
              {tag.toUpperCase()}
            </Tag>
          );
        })}
      </span>
    ),
  },
  {
    title: 'Action',
    key: 'action',
    render: (text, record) => (
      <span>
        <a>Invite {record.name}</a>
        <Divider type="vertical" />
        <a>Delete</a>
      </span>
    ),
  },
];
const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    tags: ['nice', 'developer'],
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
    tags: ['loser'],
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
    tags: ['cool', 'teacher'],
  },
];

export default function HomePage() {
  console.log('marked', marked);
  return (
    <div>
      1111
    <Card title="Default size card" extra={<a href="#">More</a>} style={{ width: 300 }}>
    <div className={styles.title}>
      HomePage111
      <div className={styles.smile}></div>
      <img src={Smileurl} alt="" />
      <SvgSmile />
    </div>

    </Card>
    <Table columns={columns} dataSource={data} />
    1111
    </div>
  );
}
就会复现

@sorrycc

**Comment by yaodong5063** [comment]
![image](https://user-images.githubusercontent.com/37628562/155291905-47d7456a-fabc-452c-b674-754e41682ad9.png)

公司项目测试迁移的时候发现这个错误
看了下多了hoist-non-react-statics和@loadable/component包，这两个包目前报错，大概是什么原因啊  
hoist-non-react-statics.cjs.js:70 Uncaught TypeError: Cannot convert undefined or null to object
    at getPrototypeOf (<anonymous>)
    at hoistNonReactStatics (hoist-non-react-statics.cjs.js:70:1)
    at resolve (loadable.esm.js:128:1)
    at loadable.esm.js:325:1
hoistNonReactStatics @ hoist-non-react-statics.cjs.js:70
resolve @ loadable.esm.js:128
(anonymous) @ loadable.esm.js:325
Promise.catch (async)
loadAsync @ loadable.esm.js:333
componentDidMount @ loadable.esm.js:230
commitLifeCycles @ react-dom.development.js:20663
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
renderClient @ browser.js:71
initialValue @ umi.ts:42
(anonymous) @ plugin.js:106
_callee$ @ umi.ts:38
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_render @ umi.ts:14
render @ umi.ts:14
./src/.umi/umi.ts @ umi.ts:48
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:6
(anonymous) @ startup:6
index.js:1 The above error occurred in the <InnerLoadable> component:

    at InnerLoadable (http://127.0.0.1:8002/umi.js:277:34)
    at LoadableWithChunkExtractor
    at Loadable
    at RemoteComponent (http://127.0.0.1:8002/umi.js:12550:93)
    at Routes (http://127.0.0.1:8002/umi.js:12407:85)
    at Router (http://127.0.0.1:8002/umi.js:65244:15)
    at BrowserRoutes (http://127.0.0.1:8002/umi.js:12386:13)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
__webpack_modules__../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
safeSetState @ loadable.esm.js:247
(anonymous) @ loadable.esm.js:334
Promise.catch (async)
loadAsync @ loadable.esm.js:333
componentDidMount @ loadable.esm.js:230
commitLifeCycles @ react-dom.development.js:20663
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
renderClient @ browser.js:71
initialValue @ umi.ts:42
(anonymous) @ plugin.js:106
_callee$ @ umi.ts:38
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_render @ umi.ts:14
render @ umi.ts:14
./src/.umi/umi.ts @ umi.ts:48
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:6
(anonymous) @ startup:6
hoist-non-react-statics.cjs.js:70 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at getPrototypeOf (<anonymous>)
    at hoistNonReactStatics (hoist-non-react-statics.cjs.js:70:1)
    at resolve (loadable.esm.js:128:1)
    at loadable.esm.js:325:1

@sorrycc

**Comment by fz6m** [comment]
antd 3 的问题使用非 esbuild 模式的 mfsu 可以跑通：

```js
  mfsu: {}
```

`name` 是 `undefined` 问题是 `@ant-design/icons-react` 这个包 3 年前 `2.0.1` 版本的问题 (详见 [这里](https://github.com/ant-design/ant-design-icons/blob/ec3bc333811c090b63e498d72b30c44e8695b945/packages/icons-react/src/components/Icon.tsx#L41) )

**Comment by yaodong5063** [comment]
> antd 3 的问题使用非 esbuild 模式的 mfsu 可以跑通：
> 
> ```js
>   mfsu: {}
> ```
> 
> `name` 是 `undefined` 问题是 `@ant-design/icons-react` 这个包 3 年前 `2.0.1` 版本的问题 (详见 [这里](https://github.com/ant-design/ant-design-icons/blob/ec3bc333811c090b63e498d72b30c44e8695b945/packages/icons-react/src/components/Icon.tsx#L41) )

[`name` 是 `undefined` 问题是 `@ant-design/icons-react` 这个包 3 年前 `2.0.1` 版本的问题 ]   这个有解决方案吗，现在没法去做antd的升级，毕竟3和4的差距蛮大的


> antd 3 的问题使用非 esbuild 模式的 mfsu 可以跑通：
> 
> ```js
>   mfsu: {}
> ```
> 
> `name` 是 `undefined` 问题是 `@ant-design/icons-react` 这个包 3 年前 `2.0.1` 版本的问题 (详见 [这里](https://github.com/ant-design/ant-design-icons/blob/ec3bc333811c090b63e498d72b30c44e8695b945/packages/icons-react/src/components/Icon.tsx#L41) )

 `name` 是 `undefined` 问题是 `@ant-design/icons-react` 这个包 3 年前 `2.0.1` 版本的问题 (详见 [这里]  这个有办法解决吗，我看了下没找到相关解决方案，现在也没法直接升级antd，antd的3和4差距还蛮大的

**Comment by yaodong5063** [comment]
@sorrycc   能提供什么参数，规避掉这个错误吗
![image](https://user-images.githubusercontent.com/37628562/155497135-1bc869ff-0cea-4671-a37a-ab5719fb2f13.png)
在umi3版本上面没有存在这个问题，但是umi3版本的热跟下实在太慢了
