### ISSUE TITLE
修改config中的layout的值，报错。

### ISSUE THREAD

**Issue by Iveon** [umijs/umi-next#392]
> info  - MFSU write cache
...\node_modules\@umijs\core\dist\config\config.js:76
                throw new Error(e);
                      ^
Error: TypeError: Cannot read properties of undefined (reading 'join')
    at ...\node_modules\@umijs\core\dist\config\config.js:76:23

**Comment by Iveon** [comment]
config中的layout定义的navTheme等部分值不会生效，但在运行时中配置可以。

**Comment by sorrycc** [comment]
Umi 4 的 layout 配置改到在运行时里配了。
