### ISSUE TITLE
request加入config.ts报Invalid config keys：request

### ISSUE THREAD

**Issue by chenliangngng** [umijs/umi-next#394]
"umi": "^4.0.0-rc.3",
package.json除了umi没有加任何东西

config/config.ts添加{request: {}}执行yarn start 报AssertionError [ERR_ASSERTION]: Invalid config keys: request

请问这个版本是不是还不能用，或者说要加什么插件吗@YdreamW

**Comment by cnyballk** [comment]
需要装下 @umijs/plugins

**Comment by chenliangngng** [comment]
> 需要装下 @umijs/plugins

请问需要安装哪个插件呢，是@umi/plugin-request吗，我试过但是是umi3的版本，不知道正确的版本是多少。看文档是直接内置的

**Comment by YdreamW** [comment]
> 

在 umi4 里，我们把一些拓展功能的插件放在了 umipro 中，这一部分的文档还没有写完，因此给开发者造成了一些困惑。

如果你想使用 request 插件的话，可以尝试使用 umipro：
`package.json` 中 `dependencies` 添加 `"@umijs/pro": ""`, 并且在 `scripts` 中 更改 `umi dev`  为 `umipro dev`

另外在 umi4 中，不再需要安装 @umijs/plugins 里的插件，这些插件的大部分都已经迁移到了 umi4 的 umipro 中。并且由于 umi4 做了一些  api 的改动，先前的插件可能不再适配。
