### ISSUE TITLE
umipro windows10跑不起来

### ISSUE THREAD

**Issue by qianyeyixia** [umijs/umi-next#409]
复现仓库: https://github.com/qianyeyixia/ys-umi4/tree/umipro
系统版本：
版本：Windows 10 专业版
版本号：20H2
操作系统内部版本：19042.1526

IDE版本：
版本: 1.65.0-insider (user setup)
提交: b7730c807c1e0fdacdcc91a854bb963715b2a89b
日期: 2022-02-28T14:37:48.095Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

电脑node版本v16.13.0
pnpm版本： 6.32.1
![image](https://user-images.githubusercontent.com/24711742/156308897-34546070-3d5f-470e-88dd-319e006d5e0e.png)

**Comment by qianyeyixia** [comment]
同事得 mac能跑起来

**Comment by xiaohuoni** [comment]
4.0.0-rc.3 之后应该支持 windows 了，尝试一下，有问题的话再反馈

**Comment by qianyeyixia** [comment]
> 

打开 mfsu的话 esbuild 报上面截图的错，
mfsu：false的话
Module build failed (from ./node_modules/.pnpm/@umijs+bundler-webpack@4.0.0-rc.4/node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
SyntaxError: D:\DemoStyle\umi\umi4\src\.umi\umi.ts: Bad character escape sequence. (6:44)报这个错, 已经是 rc4了
