### ISSUE TITLE
mfsu效果并不是太好

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi-next#411]
目前启动差不多要170秒，热更新6秒，我看node_modules里面写了.catch,可以直接跳过modules检测吗。
![image](https://user-images.githubusercontent.com/37628562/156315188-d288d930-152a-4d12-b432-d8f693df37e0.png)
@sorrycc

**Comment by yaodong5063** [comment]
![image](https://user-images.githubusercontent.com/37628562/156337592-d1b96a0d-60f7-4591-a85f-5f15c30dbbb0.png)

**Comment by sorrycc** [comment]
不开 MFSU 呢？

**Comment by yaodong5063** [comment]
![image](https://user-images.githubusercontent.com/37628562/156962350-47218bbe-fc7b-42a2-9b1b-81aa24ea30e6.png)
这边是升级的rc5版本的
![image](https://user-images.githubusercontent.com/37628562/156962382-1d9243b4-e0b7-4c53-93d0-06b5d408bf27.png)
这个是没开mfsu，感觉开没开差距不大，我也不清楚哪地方出问题了，目前还是用的




"dependencies": {
    "@sentry/react": "^6.12.0",
    "@sentry/rrweb": "^0.3.1",
    "@sentry/tracing": "^6.12.0",
    "abortcontroller-polyfill": "^1.7.3",
    "ahooks": "^2.10.9",
    "antd": "3.22.2",
    "classnames": "^2.3.1",
    "driver.js": "^0.9.8",
    "echarts": "^4.3.0",
    "echarts-wordcloud": "^1.1.3",
    "file-saver": "^2.0.5",
    "immutability-helper": "^3.1.1",
    "immutable": "^4.0.0-rc.14",
    "js-cookie": "^2.2.1",
    "lodash": "^4.17.21",
    "mc-jssdk": "^1.0.21",
    "md5": "^2.3.0",
    "memoize-one": "^5.2.1",
    "mobx": "^4.11.0",
    "mobx-react": "^6.1.1",
    "moment": "^2.29.1",
    "package": "^1.0.1",
    "path-to-regexp": "^3.1.0",
    "promise-polyfill": "^8.2.0",
    "qs": "^6.10.1",
    "react": "17.x",
    "react-amap": "^1.2.8",
    "react-color": "^2.19.3",
    "react-copy-to-clipboard": "^5.0.4",
    "react-dnd": "^10.0.2",
    "react-dnd-html5-backend": "^10.0.2",
    "react-dom": "17.x",
    "react-helmet": "^6.1.0",
    "react-infinite-scroller": "^1.2.4",
    "react-json-view": "^1.21.3",
    "react-pdf": "^4.1.0",
    "react-resizable": "^3.0.4",
    "react-router-dom": "^5.0.1",
    "react-sticky": "^6.0.3",
    "react-test-renderer": "^17.0.2",
    "react-viewer": "^3.2.2",
    "rrweb": "^0.9.14",
    "swiper": "4.x",
    "video-react": "^0.14.1"
  },
  "devDependencies": {
    "@commitlint/cli": "^12.1.4",
    "@commitlint/config-conventional": "^12.1.4",
    "@sentry/webpack-plugin": "^1.14.2",
    "@types/classnames": "^2.2.9",
    "@types/echarts": "^4.9.11",
    "@types/file-saver": "^2.0.3",
    "@types/jest": "^23.3.12",
    "@types/js-cookie": "^2.2.5",
    "@types/lodash": "^4.14.136",
    "@types/memoize-one": "^4.1.1",
    "@types/qs": "^6.5.3",
    "@types/react": "^17.0.0",
    "@types/react-copy-to-clipboard": "^5.0.2",
    "@types/react-dom": "^17.0.0",
    "@types/react-infinite-scroller": "^1.2.2",
    "@types/react-sticky": "^6.0.4",
    "@typescript-eslint/eslint-plugin": "^4.31.2",
    "@typescript-eslint/parser": "^4.31.1",
    "@umijs/plugin-esbuild": "^1.3.1",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "3.5.20",
    "@umijs/bundler-vite": "4.0.0-rc.5",
    "@weimob/xkd": "^1.2.0-beta.12",
    "@swc/core":"^1.2.150",
    "babel-eslint": "^10.1.0",
    "browserslist": "^4.17.0",
    "cross-env": "^7.0.3",
    "eslint": "^5.4.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-umi": "^1.6.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.3.2",
    "husky": "^6.0.0",
    "lint-staged": "^10.0.7",
    "mockjs": "^1.1.0",
    "prettier": "^2.2.0",
    "slash2": "^2.0.0",
    "tslint": "^5.12.0",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-react": "^3.6.0",
    "typescript": "^4.1.2",
    "umi": "4.0.0-rc.5",
    "yorkie": "^2.0.0"
  },


这边是所有的依赖

**Comment by yaodong5063** [comment]
umi4使用react-router6，<Outlet />代替了children，那之前的高阶组件怎么玩，比如mobx

@sorrycc

**Comment by yaodong5063** [comment]
umi4使用react-router6，<Outlet />代替了children，那之前的高阶组件怎么玩，比如mobx

@sorrycc

**Comment by sorrycc** [comment]
有空新建个 issue 给个复现，我试试。
