### ISSUE TITLE
关于defineConfig，若干配置报错的问题？

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi-next#413]
![image](https://user-images.githubusercontent.com/25472851/156498589-6045fdc1-c9bf-4cc0-af28-9a3a05526dfa.png)

试用了一下examples下的一些例子，速度上确实完爆Umi3，现正基于Umi4对项目进行重构，不过尝试了一番之后，发现很多配置都没法迁移，不知道是Umi4没有对相配配置进行处理还是说很多配置在Umi4就不让用了。

看commit记录貌似配置迁移的事情还没有安排上。

**Comment by xiaohuoni** [comment]
dynamicImport 配置去掉了，因为内置了这个需求。
title 最终方案还没定，可以暂时注释下
locale 配置可以正常使用才对，你看看是不是没加 plugin

**Comment by MatrixAge** [comment]
好的，了解了，locale确实是plugin没加导致的。

**Comment by ratelgogo** [comment]
> dynamicImport 配置去掉了，因为内置了这个需求。 title 最终方案还没定，可以暂时注释下 locale 配置可以正常使用才对，你看看是不是没加 plugin

dynamicImport 需要设置的话怎么办呢？

**Comment by MatrixAge** [comment]
> > dynamicImport 配置去掉了，因为内置了这个需求。 title 最终方案还没定，可以暂时注释下 locale 配置可以正常使用才对，你看看是不是没加 plugin
> 
> @xiaohuoni dynamicImport 需要设置的话怎么办呢？

现在页面默认就是动态加载的

**Comment by ratelgogo** [comment]
> > > dynamicImport 配置去掉了，因为内置了这个需求。 title 最终方案还没定，可以暂时注释下 locale 配置可以正常使用才对，你看看是不是没加 plugin
> > 
> > 
> > @xiaohuoni dynamicImport 需要设置的话怎么办呢？
> 
> 现在页面默认就是动态加载的

build的时候我想设置成false，文件太多了

**Comment by xiaohuoni** [comment]
@ratelgogo 另外提一个需求吧
