### ISSUE TITLE
UmiPro在实际项目中遇到的一些问题

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi-next#437]
![image](https://user-images.githubusercontent.com/25472851/157041730-7206d59b-2691-4ca8-8015-ec08b91ab105.png)

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/157042332-64353caa-4c0a-4c7a-814e-7dd564ad2145.png)
mfsu dev时umi.css一直爆这个。

**Comment by fz6m** [comment]
swc 不支持和 mfsu 一起用，详见终端警告，可以用 `esbuild`

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/157152273-15a1e1f4-94db-446f-8060-db76dc785911.png)

swc和mfsu不能一起使用这个是知道的，上述报错使用的是默认

**Comment by MatrixAge** [comment]
发现设置publicPath也会导致报错：
![image](https://user-images.githubusercontent.com/25472851/157158970-4a675805-e13f-455d-8355-9d9c6456e30d.png)

配置如下：
![image](https://user-images.githubusercontent.com/25472851/157159028-bf156a1a-e768-4d32-92eb-a64c9a6f8f8e.png)

![image](https://user-images.githubusercontent.com/25472851/157159057-17fbe894-dcd8-444c-897a-9f8119f913d7.png)

**Comment by qianyeyixia** [comment]
老哥用的 windows么？

**Comment by MatrixAge** [comment]
> 老哥用的 windows么？

macos

**Comment by MatrixAge** [comment]
按照umi3的方式 使用theme配置less变量无法生效。

**Comment by qianyeyixia** [comment]
> 

好吧，我win umi4能跑起来 umipro跑不起来，提了issues,他们说能跑起来换了有好几个同事都跑不起来
