### ISSUE TITLE
是否能增加一个@umijs/mfsu 适配 create-react-app 的example

### ISSUE THREAD

**Issue by AlbertLin0923** [umijs/umi-next#457]
使用了 @umijs/mfsu@4.0.0-rc.5 ，想改造公司项目（基于create-react-app@5.0.0），发现一直卡在info  - MFSU write cache...  可能是我自己写法错误

**Comment by fz6m** [comment]
1. 使用的什么方式修改 webpack config ？
2. 可以贴一下你的 config 方式

**Comment by fz6m** [comment]
> 使用了 @umijs/mfsu@4.0.0-rc.5 ，想改造公司项目（基于create-react-app@5.0.0），发现一直卡在info - MFSU write cache... 可能是我自己写法错误

把 `WebpackManifestPlugin` 这个插件给去掉，否则确实会一致卡 write ，两个冲突了额。

<img width="442" alt="image" src="https://user-images.githubusercontent.com/59400654/157639317-054670fe-988d-440c-b4f4-541a1fd4391f.png">

**Comment by fz6m** [comment]
> > 
> 
> 似乎还是不行 ![image](https://user-images.githubusercontent.com/24648689/157643176-ed5832b8-c511-4069-a517-c9cf9af64a36.png) 你可否贴一下配置，可能配置某个地方出错了

See [fz6m/cra-with-mfsu](https://github.com/fz6m/cra-with-mfsu)

**Comment by AlbertLin0923** [comment]
> See fz6m/cra-with-mfsu

感谢！配置可用，但是我发现一个问题，似乎@umijs/mfsu@4.0.0-rc.6不支持纯js项目？ 使用npx create-react-app XXX 搭建的js项目，按照这个配置，会报错，换成typescript就好了

报错信息如下：

![Snipaste_2022-03-11_16-00-36](https://user-images.githubusercontent.com/24648689/157826603-3988d2d2-6406-453a-9713-e05b3d155de7.png)

**Comment by fz6m** [comment]
> > See fz6m/cra-with-mfsu
> 
> 感谢！配置可用，但是我发现一个问题，似乎@umijs/mfsu@4.0.0-rc.6不支持纯js项目？ 使用npx create-react-app XXX 搭建的js项目，按照这个配置，会报错，换成typescript就好了； 另外我发现 examples/mfsu-independent 也是typescript项目
> 
> 报错信息如下：
> 
> ![Snipaste_2022-03-11_16-00-36](https://user-images.githubusercontent.com/24648689/157826603-3988d2d2-6406-453a-9713-e05b3d155de7.png)

解法：

```js
rename `src/index.js` to `src/index.jsx`
rename `src/App.js` to `src/App.jsx`
// ......
```

使用了 React 节点的文件，需要以 `.jsx` 或 `.tsx` 结尾，否则 esbuild 无法处理他们

**Comment by AlbertLin0923** [comment]
@fz6m 遇到了一个问题，项目 package.json 配置 homepage 字段 后，使用mfsu会报错，报错信息如下：

![Snipaste_2022-03-12_16-55-01](https://user-images.githubusercontent.com/24648689/158011446-d804a2ea-79ae-4630-bd67-86481141d838.png)

![Snipaste_2022-03-12_16-49-29](https://user-images.githubusercontent.com/24648689/158011478-fc16185e-4214-4594-b9aa-75fd021ba60c.png)

似乎在配置里面也没有看到可以配置的选项

![Snipaste_2022-03-12_17-01-45](https://user-images.githubusercontent.com/24648689/158011526-dcc8db16-7304-4881-979f-d8293d9c2e8c.png)

**Comment by fz6m** [comment]
用 `.env.production` 的 `PUBLIC_URL` 解吧，不要干扰到开发环境。

cra 是个重型桶，有一堆不必要的约定，关于 `homepage` 的部分你可以自己读一下他的配置链路，这是 cra 基础。

**Comment by AlbertLin0923** [comment]
> 用 .env.production 的 PUBLIC_URL 解吧，不要干扰到开发环境。
之所以配置homepage是因为项目是微前端模式，本地开发会开启多个服务，A项目根 路径为 / ，B项目根路径为 /XXX；然后A项目启用mock服务，将请求 /XXX 的链接可以转发到B项目，想以此来模拟线上微前端环境 😄
