### ISSUE TITLE
[BUG] @umijs/plugins 升级到 `4.0.0-rc.6` 后 tailwindcss 失效！

### ISSUE THREAD

**Issue by Codennnn** [umijs/umi-next#460]
![image](https://user-images.githubusercontent.com/47730755/157628989-4545bfc4-49ed-4e17-bb3b-a34a403a86cf.png)

`4.0.0-rc.5` 正常，`4.0.0-rc.6` 有此问题。

重现仓库：https://github.com/Codennnn/umi4-test.git

**Comment by ken20001207** [comment]
@Codennnn `4.0.0-rc.6` 之后 Tailwindcss 插件需要透过配置开启 😂

```ts
// .umirc.ts

export default {
  plugins: [require.resolve('@umijs/plugins/dist/tailwindcss')],
  tailwindcss: {} // add this!
}
```

Reference: https://github.com/umijs/umi-next/commit/55b261040707044e19ad1bf8ff2f472b3baffe3e

---

@sorrycc 云谦老师，是不是可以考虑改成自动根据 `api.paths.cwd` 下是否有 `tailwind.config.js` 来判断插件启用？

**Comment by sorrycc** [comment]
为了统一，umi 4 的 plugins 约定全部通过配置开启，配置开启后可以再加一层 tailwind.config.js 的判断。

**Comment by fz6m** [comment]
> @Codennnn `4.0.0-rc.6` 之后 Tailwindcss 插件需要透过配置开启 😂
> 
> ```ts
> // .umirc.ts
> 
> export default {
>   plugins: [require.resolve('@umijs/plugins/dist/tailwindcss')],
>   tailwindcss: {} // add this!
> }
> ```
> 
> Reference: [55b2610](https://github.com/umijs/umi-next/commit/55b261040707044e19ad1bf8ff2f472b3baffe3e)
> 
> @sorrycc 云谦老师，是不是可以考虑改成自动根据 `api.paths.cwd` 下是否有 `tailwind.config.js` 来判断插件启用？

cra 就是这么做的，自动识别 tailwind 配置文件

**Comment by xiaohuoni** [comment]
不约定不约定。至少要有一个地方有配置。
