### ISSUE TITLE
access 插件比umi3 少导出一个Access组件

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi-next#461]

**Comment by a97077088** [comment]
我也一样

**Comment by a97077088** [comment]
解决了，access开启用法如下: 
安装rc6以上的版本，不要直接install，因为目前npm的版本还在beta版本,我也不知道为啥

安装依赖: pnpm install @umijs/pro@4.0.0-rc.6

1.在项目根目录建立 access.ts文件(跟.umirc.ts一个目录)
2.打开 .umirc.ts设置如下:
`export default {
npmClient: 'pnpm',
  mfsu:true,
  access:{},
  initialState:{},
  model:{},
}`
3.修改package.json 里面的启动模式为umipro,例如dev
`umipro dev`

**Comment by Nokecy** [comment]
#517
