### ISSUE TITLE
和turborepo一起使用报错

### ISSUE THREAD

**Issue by cl1107** [umijs/umi-next#475]
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/21985353/158121298-6a6caf48-656e-414d-897c-ece208c9c215.png">
复现步骤
1. npx create-turbo@latest 新建一个turborepo仓库
2. cd apps && mkdir umi && cd umi
3. pnpx create-umi@next
复现仓库
https://github.com/cl1107/umi-turbo

**Comment by fz6m** [comment]
See 

https://github.com/vercel/next.js/releases/tag/v12.0.9
https://github.com/vercel/next.js/pull/33442

把仓库里面 docs / web 两个 next 项目的 `next` 升到最新版就可以了

**Comment by cl1107** [comment]
> See
> 
> https://github.com/vercel/next.js/releases/tag/v12.0.9 [vercel/next.js#33442](https://github.com/vercel/next.js/pull/33442)
> 
> 把仓库里面 docs / web 两个 next 项目的 `next` 升到最新版就可以了

可以了
