### ISSUE TITLE
启用 @umijs/plugins/dist/tailwindcss  插件之后，使用 umi 命令每次都会 spawn 一个 tailwindcss 进程

### ISSUE THREAD

**Issue by stormslowly** [umijs/umi-next#482]
原因是使用了 `api.onStart`, 启动 umi cli 就会执行 onStart 注册的函数。
后继看看能不能放在 onComplier 事件下面去。

**Comment by sorrycc** [comment]
api.onStart 判断 api.name 是否为 dev 或 build 吧。

**Comment by stormslowly** [comment]
> api.onStart 里判断下 api.name 是否为 dev 或 build 。

OK

**Comment by stormslowly** [comment]
目前看 

* tailwindcss
* nocss 

两个插件要改，后继这类编译资源类的插件还是要给一个单独抽象一个事件会不会好一点。
