### ISSUE TITLE
umi4 如何添加sass 支持,能简单给一个实例吗

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi-next#487]

**Comment by stormslowly** [comment]
@Nokecy   umi4 已经 内置了 sass-loader ，你只要以下几步就能使用 sass 

1.  安装 sass 依赖， `npm i sass -D`
2.  如果是使用 typescript 的话，在项目的根目录的 `typings.d.ts` 文件中添加  `declare module '*.scss';`  or  `declare module '*.sass';`  
3.  记得修改原来的 less 文件变成 sass，和 把 `import  style from 'xxx.less'` 改成 `xxx.scss`

**Comment by stormslowly** [comment]
后继我会添加一个 with-sass 到项目的 examples 里面
