### ISSUE TITLE
locale 没有导出 getIntl 和 getLocale

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi-next#489]

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/158516732-49de16d2-c93c-4d21-80b7-6717b15530fe.png)

const locale_info = useIntl()

console.log( locale_info )

用这里面的信息也能获取到当前locale。

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/158569351-cec7b00a-a166-4b6c-9d4c-ee6bfce191ab.png)

不知道为啥不导出了，先将就着用吧，备用方案 https://formatjs.io/docs/getting-started/installation/ 自己载入。
