### ISSUE TITLE
HashHistory 时的路径访问问题

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi-next#547]
```
http://127.0.0.1:8001/users    首页
http://127.0.0.1:8001/aa    找不到页面
http://127.0.0.1:8001/#/users  users页面
```
![image](https://user-images.githubusercontent.com/11746742/160674111-26812a73-c716-4a8b-8e63-de676e23afc1.png)

**Comment by sorrycc** [comment]
Fixed via https://github.com/umijs/umi-next/commit/12fb0ea48119804fef9e2088d8794dacf75664c3
