### ISSUE TITLE
在项目下用npm install antd，和采用umi antd插件，两种方式有什么区别？

### ISSUE THREAD

**Issue by asialiugf** [umijs/umi-next#550]
在项目下用npm install antd，和采用umi antd插件，两种方式有什么区别？ 对开发有哪些影响

**Comment by chenliangngng** [comment]
umi的antd版本不一定会跟上antd最新版本，重新install可以用更新版本或者指定版本的antd

**Comment by sorrycc** [comment]
umi 4 的文档还没写，参考 umi 3 的，https://umijs.org/plugins/plugin-antd
