### ISSUE TITLE
大概什么时候到rc阶段，迫不及待想要体验下船新版本

### ISSUE THREAD

**Issue by winter-ice** [umijs/umi-next#56]
看了umi的新版本以及各种相关的插件库，例如layout，access，model，这些，很是激动，感觉新版本使用起来会是全新的体验，想问下大概什么时候能到rc阶段，（有个readme也好啊）

**Comment by sorrycc** [comment]
3.1 正式发布。

**Comment by winter-ice** [comment]
文档的优先级是最后么？目前没有体验流程？

**Comment by sorrycc** [comment]
下周陆续开始写，和 umi 使用上差不多的。
