### ISSUE TITLE
umi 4 layout 404页面不好用了

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi-next#569]
访问一个不存在的页面时返回 Cannot Get /xxxx/xxxx UMI3可以进入Layout 并显示404

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-next/projects/3#card-78518961
还没实现

**Comment by Nokecy** [comment]
@xiaohuoni  大佬这个能不能提升一下优先级~~~ ,升级umi4就差这一个了

**Comment by xiaohuoni** [comment]
云谦老师，正在处理中...

**Comment by Nokecy** [comment]
~~ 好的 谢谢！！ 已经自己先弄了个插件 改了下路由数据，搞定了，等正式版
