### ISSUE TITLE
功能请求 plugin-request IRequest 返回结果支持泛型

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi-next#570]

**Comment by Nokecy** [comment]
像umi3 一样将IRequest 换成 这样可行 ？@xiaohuoni
- `
  - interface RequestMethodInUmi<R = false> {
  <T = any>(
    url: string,
    options: RequestOptionsWithResponse & { skipErrorHandler?: boolean },
  ): Promise<RequestResponse<T>>;
  <T = any>(
    url: string,
    options: RequestOptionsWithoutResponse & { skipErrorHandler?: boolean },
  ): Promise<T>;
  <T = any>(
    url: string,
    options?: RequestOptionsInit & { skipErrorHandler?: boolean },
  ): R extends true ? Promise<RequestResponse<T>> : Promise<T>;
}
 `

**Comment by xiaohuoni** [comment]
@sorrycc cc

**Comment by YdreamW** [comment]
已添加
