### ISSUE TITLE
vite 模式不支持 APP_ROOT

### ISSUE THREAD

**Issue by xierenyuan** [umijs/umi-next#584]
复现demo
https://stackblitz.com/edit/github-k3btck?file=client/config/config.ts

看起来是这里的处理导致的
https://github.com/umijs/umi-next/blob/master/packages/bundler-vite/src/build.ts#L62

尝试 这样处理了下. 产物生成了 但是 index.html  生成有问题
```ts
 if (cwd !== process.cwd() && process.env.APP_ROOT) {
    cwd = process.cwd()
 }
```

**Comment by PeachScript** [comment]
> 看起来是这里的处理导致的
> https://github.com/umijs/umi-next/blob/master/packages/bundler-vite/src/build.ts#L62

vite 层不感知 `APP_ROOT`，看下 preset-umi 下发 cwd 的逻辑是否正确
