### ISSUE TITLE
[RFC] @umijs/lint

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi-next#6]
## @umijs/lint

包含 eslint 、prettier、stylelint 配置的合集包。

### 原因

规范 Umi & Bigfish 项目的代码规范及统一团队代码风格。

### 目标

- lint 规则可扩展，可基于这个包扩展出项目/业务线的 lint 合集。
- 稳定，不会因为升级而导致报错，阻碍构建进程。
- 跟进社区，及时将最新、有用的规则同步。
- umi 仓库消费这份 lint 规则

### 方案一

1. 将 [@umijs/fabric](https://github.com/umijs/fabric) 规则拿到 @umijs/lint 中，锁中间 minor 版本（锁具体版本？）。
1. 加上测试用例，尽可能全的测试用例，每次发包时，保证之前的代码风格，lint 不挂。
1. 导出 `eslint`、`prettier`、`stylelint` 实例，Umi 中使用到的全通过来消费：

```js
import { eslint, prettier, stylelint } from '@umijs/lint'
```

好在：
1. 稳定性能保证，不会因为 eslint 自身升级而造成 umi 项目 lint 失败

不好在：
1. 需要维护包的成本较高，定期维护
2. 用户项目里要安装每个 `eslint-plugin-*` 包，即使没有用到 TypeScript，也得安装 `@typescript-eslint/parser`

### 方案二

1. 通过手动 `umi invoke` 来将包里的 eslint 写到用户项目 `package.json` 中，类似 vue-cli 的做法，这样做到按需安装

好在：
1. 按项目特性安装包，减少 lint 包出错概率

不好在：
1. install 前会多一步操作，对用户习惯有挑战
2. 写包到用户的 `devDependencies` 不是好的做法

**Comment by sorrycc** [comment]
我的想法，

1. 这个包只包含规则，不包含命令
2. eslint 的 require 得 hack 下，不能从根路径找，从根路径找感觉随时会挂（有个补丁的，一下子没找到）

**Comment by chenshuai2144** [comment]
最好用的 hack 就是这个了
```

const eslintFolder = path.join(path.dirname(require.resolve('eslint')), '..');

const moduleResolverPath = path.join(eslintFolder, 'lib/shared/relative-module-resolver');
const ModuleResolver = require(moduleResolverPath);

ModuleResolver.resolve = function(moduleName: string) {
  return require.resolve(moduleName);
};

```

**Comment by sorrycc** [comment]
@chenjsh36 这个 hack 的来源是哪？我找了下没有找到。

**Comment by chenshuai2144** [comment]
是 github 的一个 issue 里面的。
他们也碰上了 找不到 eslint 依赖的问题

**Comment by sorrycc** [comment]
@chenshuai2144 地址呢？

**Comment by xiaohuoni** [comment]
@sorrycc
https://github.com/eslint/eslint/issues/3458#issuecomment-541329579

**Comment by afc163** [comment]
https://github.com/umijs/umi-next/issues/3
