### ISSUE TITLE
运行 pnpm dev 报错

### ISSUE THREAD

**Issue by trueLoving** [umijs/umi-next#618]
## Bug Description

![image](https://user-images.githubusercontent.com/44056372/163657642-003f5a2c-4e51-45df-b30a-ee7d9e8552fa.png)

## Reproduction

1. git clone https://github.com/umijs/umi-next.git   
2. cd umi-next 
3. pnpm i
4. cd packages/umi
5. pnpm dev

## System Info

1. System: Windows10 WSL2（Ubuntu 16）
2. Node:  v16.14.2
3. pnpm: v6.32.4

**Comment by sorrycc** [comment]
需要先 build。
