### ISSUE TITLE
[文档] 官网「运行时配置」页面报错，显示空白

### ISSUE THREAD

**Issue by liuxingyu521** [umijs/umi-next#645]
链接地址： https://next.umijs.org/docs/api/runtime-config

猜测原因： md 内容里包含了 `patchRoutes({ routes })` 这段内容，mdx 解析的时候误把大括号解析成 jsx 表达式， 可以在 `{` 之前加转义符？类似这样 `patchRoutes(\{ routes \})` 😃 

![image](https://user-images.githubusercontent.com/15321445/164385603-c66c1161-7585-491b-9016-13061c2c93d7.png)

**Comment by xiaoliu1990** [comment]
还有个问题，左侧导航滚动后，每次点击会重置到最顶点，没有定位在当前滚动的位置，这样也不太好用
