### ISSUE TITLE
[严重性能问题] 现umi 4.*都会出现layout重渲染的问题，经测试，是由于React Router v6配置变更导致

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi-next#666]
使用Umi4开发新项目了一段时间，相比于v3，一个字“快”。

以下情况皆为没有主动声明路由，使用umi自动生成路由的情况：

昨天突然发现Layout上的NavMenu，它的Logo老在闪烁，经排查，是**整个应用都会在路由切换之后重新渲染**，“性能爆炸”了，属于是。

然后拿v3试了一下，v3的Layout不会出现这样的问题，一番Google之后发现，是React Router v6的配置问题。

![image](https://user-images.githubusercontent.com/25472851/164837694-b92947d2-943d-458f-9408-fc5bb88993d9.png)

![image](https://user-images.githubusercontent.com/25472851/164837719-55d07161-9029-4d25-b77f-a7a2e89087a6.png)

如何复现，任意v4项目即可复现。

这是官方的Layout例子，可能与v5版本有所不用，plugin-layout需要适配一下：
![image](https://user-images.githubusercontent.com/25472851/164842495-0bd73eab-f7d0-4b6c-ac3e-6374a6e8f5d6.png)

**Comment by sorrycc** [comment]
1、npx umi -v 看下是什么版本
2、试试 umi@4.0.0-canary.20220422.3 是否还有这个问题

**Comment by MatrixAge** [comment]
> 1、npx umi -v 看下是什么版本 2、试试 umi@4.0.0-canary.20220422.3 是否还有这个问题

这个版本没问题，👍。
