### ISSUE TITLE
提升单测测试覆盖率

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi-next#67]
## 背景

为了 umi 底层质量更高，大家可以一起来补单测，可以从[这里](https://codecov.io/gh/umijs/umi-next/tree/master/packages)挑选自己感兴趣的模块，回复到该 issue，避免重复。

![image](https://user-images.githubusercontent.com/13595509/74750117-2e1e2e00-52a6-11ea-9686-465b1df906ec.png)

## 规范

测试用例与需要测试的文件写在一起，例如：

```bash
- src
   - index.test.ts
   - index.ts
   - bar
      - bar.ts
      - bar.test.ts
```

用例尽量以 `test` 平铺展开，避免嵌套式写法。

```js
test('bar', () => {

})

test('foo', () => {

})
```

有关插件的方法见 [《插件测试》](https://github.com/umijs/umi-next/blob/master/docs/plugin/test.md)

------

## Background

For improving the quality of the umi repo, you can make up the order test together. You can choose the modules you are interested in from [here](https://codecov.io/gh/umijs/umi-next/tree/master/packages), reply to this issue to avoid duplication.

![image](https://user-images.githubusercontent.com/13595509/74750117-2e1e2e00-52a6-11ea-9686-465b1df906ec.png)

## Specification

Test cases are written with the files to be tested, for example:

```bash
-src
   -index.test.ts
   -index.ts
   -bar
      -bar.ts
      -bar.test.ts
```

Use cases should be expanded as `test` as possible to avoid nested writing.

```js
test ('bar', () => {

})

test ('foo', () => {

})
```

For the method of plugins, please refer to [Plugin Testing](https://github.com/umijs/umi-next/blob/master/docs/plugin/test.md)

**Comment by xiaohuoni** [comment]
packages/utils @xiaohuoni 
utils/src/winEOL 
utils/src/Generator

**Comment by xiaohuoni** [comment]
preset-built-in/src @xiaohuoni
