### ISSUE TITLE
为何把 umi-request 换成 axios 了？

### ISSUE THREAD

**Issue by wanghaida** [umijs/umi-next#692]
实际使用体验，umi-request 确实比 axios 好用。

https://github.com/umijs/umi-request#umi-request-vs-fetch-vs-axios

**Comment by leshalv** [comment]
> 实际使用体验，umi-request 确实比 axios 好用。
> 
> https://github.com/umijs/umi-request#umi-request-vs-fetch-vs-axios

umi-request 更新都停了，也不维护了。

**Comment by wanghaida** [comment]
> umi-request 更新都停了，也不维护了。

太可惜了，功能强大，解析大 json 速度又快。axios 在请求大 json 时会耗费好长时间（不知现在修复了没有）。
