### ISSUE TITLE
max 配置 运行时request报错

### ISSUE THREAD

**Issue by ColinChen2** [umijs/umi-next#707]
在src里的app.ts中配置了request，就会报错。去除就恢复正常。
```
import { RequestConfig } from '@@/plugin-request';

export const request: RequestConfig = {
  // other options you want
  errorConfig: {},
};
```

版本：
"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@umijs/max": "4.0.0-canary.20220427.1",
    "antd": "^4.20.0"
  },

报错：
<img width="1258" alt="Screen Shot 2022-04-27 at 5 46 01 PM" src="https://user-images.githubusercontent.com/7310875/165491754-c59f3904-8757-4ddf-9bc1-f3948552a314.png">

**Comment by ColinChen2** [comment]
项目配置文件里配的是
```
request: {
    dataField: '',
 },
```

**Comment by YdreamW** [comment]
`import { RequestConfig } from '@@/plugin-request';` 
改为
`import type { RequestConfig } from '@@/plugin-request';`
试试。
旧文档 demo 好像没加 type，新文档已经补上了。
