### ISSUE TITLE
bug: path id conflicts between multiple svgr

### ISSUE THREAD

**Issue by PeachScript** [umijs/umi-next#756]
## Description

引入多个带 path id 的 svgr 时，相互的 id 会冲突

## Steps to reproduce

`examples/boilerplate` 中，找两个有 path id 的 svg 引入可以复现，比如 Bigfish 官网的 svg

相关 issue：https://github.com/svg/svgo/issues/674#issuecomment-324193597

**Comment by xiaohuoni** [comment]
https://react-svgr.com/docs/options/#svgo
看文档应该是已经处理了，我进一步跟进解决这个问题。
