### ISSUE TITLE
@umijs/plugin-layout插件建议

### ISSUE THREAD

**Issue by LanJamRom** [umijs/umi-next#762]
支持使用iconfont渲染路由表中的icon属性

**Comment by wangxingkang** [comment]
目前好像就支持吧

**Comment by LanJamRom** [comment]
> 目前好像就支持吧

在antd-pro示例中引入就报错，似乎是patchRoutes渲染的是@ant-design/icons对应的icon，找不到直接报错

**Comment by LanJamRom** [comment]
> 目前好像就支持吧

iconfontUrl并未在plugin-layout中并没有使用

**Comment by LanJamRom** [comment]
> 目前好像就支持吧

iconfontUrl在plugin-layout中并未正确配置上

**Comment by LanJamRom** [comment]
看看能不能先处理一下这个，userConfig 好多个属性都没配置上，这样prod也用不了

**Comment by xiaohuoni** [comment]
`好多个属性` 指哪些属性？

**Comment by LanJamRom** [comment]
navTheme、contentWidth、iconfontUrl、splitMenus等，希望能增加运行时配置，最好就是能合并userConfig

**Comment by xiaohuoni** [comment]
讲道理，pro-layout的api应该可以透传过去？

**Comment by LanJamRom** [comment]
目前不行，umi3的plugin-layout就有处理

**Comment by ratelgogo** [comment]
@LanJamRom 后来解决了吗？我是提示icon找不到
