### ISSUE TITLE
umi-rc19 buid 出错

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi-next#796]
ENOENT: no such file or directory, open 'D:\Work\React\WMS-React\dist\*.44120547.async.js'] 

[umi.log](https://github.com/umijs/umi-next/files/8746078/umi.log)

**Comment by sorrycc** [comment]
给的信息太少了，为啥会有 *.xxx 的文件。

**Comment by gggso** [comment]
一样把依赖升级到rc19 报错了。
<img width="883" alt="image" src="https://user-images.githubusercontent.com/6212790/169970588-a6118e6b-2db0-49bf-ad16-1befa9184e52.png">

**Comment by fz6m** [comment]
@gggso 你用的这套是 @umijs/max

**Comment by Nokecy** [comment]
Build 还是会出错 但是产出物可用。。。。
![image](https://user-images.githubusercontent.com/12318131/172745032-4d254cff-5dc9-4e21-8735-b30686a42491.png)
