### ISSUE TITLE
proLayout插件改动 导致低版本proLayout 不可用了 

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi-next#819]
https://github.com/umijs/umi-next/blob/ba87c5bf5e0735997ce5ed8c05674a4c8ec1437d/packages/plugins/src/layout.ts#L73

proLayout 6.38.0 版本ProLayout 导出方式错误

**Comment by kaoding** [comment]
https://github.com/ant-design/pro-components/commit/7233890d1d3291f9ce5b804fe813f2fa82e7bfb3

**Comment by Nokecy** [comment]
proLayout     v6.38.6 
umi               v4.0.0-rc.20
![image](https://user-images.githubusercontent.com/12318131/170918511-b33143ae-37a4-4f16-ac8a-d66e065dde3b.png)

**Comment by Nokecy** [comment]
@kaoding
