### ISSUE TITLE
mfsu 开启私有包引入抛错

### ISSUE THREAD

**Issue by Onlylonger** [umijs/umi-next#843]
复现仓库：https://github.com/Onlylonger/umi4-demo

```sh

git clone git@github.com:Onlylonger/umi4-demo.git

yarn && yarn start

```
浏览器运行时报错

**Comment by fz6m** [comment]
你的 `es/fields/input/index` 这个组件存在逻辑问题（可能是语法错误、逻辑问题等）

如果你尝试：

```ts
import { TextOverLength } from "@chicv/admin-components/es/ui";
```

避开错误文件的索引就不会报错，不使用 mfsu 时，只是 webpack 帮你抑制了没使用到的组件中的致命问题，由于使用 mfsu 时会全量预编译所以当即暴露了这个问题。

<img width="996" alt="image" src="https://user-images.githubusercontent.com/59400654/171913996-8f517887-03ba-430e-9908-43d26249df62.png">
