### ISSUE TITLE
尝试开启 `qiankun` 微前端插件导致启动错误。

### ISSUE THREAD

**Issue by Codennnn** [umijs/umi-next#850]
根据官方文档提及的 [微前端](https://next.umijs.org/docs/max/micro-frontend) 配置父应用步骤，我作了如下配置：

```ts
// .umirc.ts

plugins: [
  require.resolve('@umijs/plugins/dist/qiankun'),
],

qiankun: {
  master: {
    apps: [],
  },
},
```

我所使用的是 `@umijs/plugins@4.0.0-rc.12`。

结果导致启动项目是发生以下错误：

![Snipaste_2022-06-06_14-29-13](https://user-images.githubusercontent.com/47730755/172107410-6b0c3e24-d795-4031-bfa9-32a5e5803872.jpg)

我无法理解这个错误信息，是否是我的配置有误导致的呢？如果是，请问该如何正确配置？🤒

**Comment by fz6m** [comment]
请尝试将 umi 相关依赖（`umi` / `@umijs/plugins` 等）升级至最新的 [rc](https://www.npmjs.com/package/umi) 版本后再检查是否存在问题。

**Comment by Codennnn** [comment]
>

**Comment by Codennnn** [comment]
> 请尝试将 umi 相关依赖（`umi` / `@umijs/plugins` 等）升级至最新的 [rc](https://www.npmjs.com/package/umi) 版本后再检查是否存在问题。

将 `umi` `@umijs/plugins` 升级至 `4.0.0-rc.21` 依然存在此问题。
