### ISSUE TITLE
umi4 external 配置后的 index.html script 排序

### ISSUE THREAD

**Issue by Onlylonger** [umijs/umi-next#852]
进行 external 配置，默认构建的产物 会在 最前面，怎么控制 产物的 script 排序, 或者说默认在最后.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/19505200/172139773-c705f4d8-b5f0-4d6a-a523-8f41f3b80767.png">

<img width="758" alt="image" src="https://user-images.githubusercontent.com/19505200/172139945-5ed1d7af-90aa-40bb-a61d-b2ad7631a923.png">

**Comment by fz6m** [comment]
目前你可以尝试：

```bash
  touch plugin.ts
```

```ts
// ${projectRoot}/plugin.ts

import { IApi } from 'umi';

export default (api: IApi) => {
  api.modifyHTML(($) => {
    $('head').append([
      `<script src='https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js'></script>`,
      `<script src='others...'></script>`
    ])
    return $;
  });
};
```

**Comment by xiaohuoni** [comment]
> 目前你可以尝试：
> 
> ```shell
>   touch plugin.ts
> ```
> 
> ```ts
> // ${projectRoot}/plugin.ts
> 
> import { IApi } from 'umi';
> 
> export default (api: IApi) => {
>   api.modifyHTML(($) => {
>     $('head').append([
>       `<script src='https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js'></script>`,
>       `<script src='others...'></script>`
>     ])
>     return $;
>   });
> };
> ```

这不是他要的，指是指 script 配置的 js 应该在 umi.js 之前

**Comment by xierenyuan** [comment]
如果 `[headScripts](https://next.umijs.org/zh-CN/docs/api/config#headscripts)` 场景不合适的话, 是不是实现 scripts 内容放在 `umi.js` 之前,  看起来还是比较合理的诉求。

**Comment by postbird** [comment]
这个 issue 关闭的原因是什么呢？目前遇到了同样的问题 @sorrycc
