### ISSUE TITLE
umi4 使用fetch在浏览器控制台手动加载时404

### ISSUE THREAD

**Issue by dashaowang** [umijs/umi-next#853]
## What happens?

我在使用umi4作为子系统时，发现加载过程中子系统入口报了404错误，然后我将url直接复制到浏览器新的页签打开，是能够正常加载的。同时，在浏览器控制台直接使用fetch加载时也报了404错误。

## Context

- **Umi Version**:4.0.0-rc.20
- **Node Version**:16.14.0
- **Platform**:windows

**Comment by fz6m** [comment]
See https://github.com/umijs/umi-next/blob/55e6be1767dce4b83698e2050d7c831f280a5555/packages/plugins/libs/qiankun/master/MicroApp.tsx#L143-L147

**Comment by dashaowang** [comment]
> 

配置headers确实可以解决这个问题  但是umi3的qiankun插件好像没有这样配置
