### ISSUE TITLE
使用mfsu without umi时，react 开发模式报错

### ISSUE THREAD

**Issue by SamWeichangyue** [umijs/umi-next#856]
![image](https://user-images.githubusercontent.com/30724369/172332054-cda65ef0-6d4e-458e-9d2c-3b0570c8c474.png)
![image](https://user-images.githubusercontent.com/30724369/172332171-eb897329-1974-41c2-a384-4e419286b7c4.png)
尝试使用mfsu 在原本的 webpack5 开发环境配置中，根据[官网例子](https://next.umijs.org/blog/mfsu-independent-usage)一步步设置，由于发现原项目使用js来编写，所以暂时无法使用esbuild，所以配置如下图设置: 
![image](https://user-images.githubusercontent.com/30724369/172333668-8561057d-3eda-4506-a203-a74f6e482bd3.png)

**Comment by SamWeichangyue** [comment]
> 很快的信息，我们暂时出现了大部分问题。请稍后提供该[重新](https://stackoverflow.com/help/minimal-reproducible-example)开启问题。谢谢
由于历史原因，react项目代码是纯js，在查询mfsu源码得知必须使用 .ts 或 .tsx文件做entry。疑问是 buildDepWithESBuild：false 是否支持纯js 项目开启mfsu

**Comment by SamWeichangyue** [comment]
@sorrycc 抱歉打扰，最小复现demo：https://github.com/SamWeichangyue/test-mfsu.git
查阅了mfsu源码：有几个疑问：
1.mfsu 源码中 会检测webpack entry 是否是index.ts/.tsx。是否意味着不支持.js文件做entry
2.如果原有react项目（项目皆为纯js代码文件）想使用mfsu 该如何升级

**Comment by sorrycc** [comment]
@stormslowly 有空跟下这个。

**Comment by stormslowly** [comment]
> @sorrycc 抱歉打扰，最小复现demo：https://github.com/SamWeichangyue/test-mfsu.git 查阅了mfsu源码：有几个疑问： 1.mfsu 源码中 会检测webpack entry 是否是index.ts/.tsx。是否意味着不支持.js文件做entry 2.如果原有react项目（项目皆为纯js代码文件）想使用mfsu 该如何升级
不好意思最近刚有时间看

我过了下源码，可以接受 js 文件作为 entry ，同时目前 mfsu 独立使用的文档有点问题，到时候我们一起改了~ 
敬爱的 Umi4 用户请稍候下~  ：P

**Comment by stormslowly** [comment]
> @sorrycc 抱歉打扰，最小复现demo：https://github.com/SamWeichangyue/test-mfsu.git 查阅了mfsu源码：有几个疑问： 1.mfsu 源码中 会检测webpack entry 是否是index.ts/.tsx。是否意味着不支持.js文件做entry 2.如果原有react项目（项目皆为纯js代码文件）想使用mfsu 该如何升级

参考下新的 文档 和 [example](https://github.com/umijs/umi-next/blob/master/examples/mfsu-independent/webpack.config.js)

更新下依赖 到 @umijs/max  4.0.0-canary.20220614.2

**Comment by SamWeichangyue** [comment]
@stormslowly  抱歉打扰 纯js问题解决了，但现在有个新的问题
demo：https://github.com/SamWeichangyue/test-mfsu.git . 
"@umijs/mfsu": "4.0.0-rc.23", 对文档里有个字段不是很理解 buildDepWithESBuild
我将demo 中的 buildDepWithESBuild改为 false; 然后会pnpm dev:mfsu 得到一个报错
![image](https://user-images.githubusercontent.com/30724369/174207312-57af507f-e421-4273-b6cf-ce1147108409.png)
文档中这个字段是控制是否开启esbuild,  

- 当buildDepWithESBuild 为true 并且 loader 为esbuildloader 才为真正的开启esbuild
- 那buildDepWithESBuild 为true ，loader还使用babel-loader 是走 babel-loader
- 那buildDepWithESBuild 为 false 时？会得到一个报错

**Comment by stormslowly** [comment]
> @stormslowly 抱歉打扰 纯js问题解决了，但现在有个新的问题 demo：https://github.com/SamWeichangyue/test-mfsu.git . "@umijs/mfsu": "4.0.0-rc.23", 对文档里有个字段不是很理解 buildDepWithESBuild 我将demo 中的 buildDepWithESBuild改为 false; 然后会pnpm dev:mfsu 得到一个报错 ![image](https://user-images.githubusercontent.com/30724369/174207312-57af507f-e421-4273-b6cf-ce1147108409.png) 文档中这个字段是控制是否开启esbuild,
> 
> * 当buildDepWithESBuild 为true 并且 loader 为esbuildloader 才为真正的开启esbuild
> * 那buildDepWithESBuild 为true ，loader还使用babel-loader 是走 babel-loader
> * 那buildDepWithESBuild 为 false 时？会得到一个报错

那buildDepWithESBuild 为 false 时？会得到一个报错 

这个你看下 上个回复exmaple 链接，msfu setWebpackConfig  需要一个 depConfig 的字段

另外两个我确认下

**Comment by SamWeichangyue** [comment]
> > @stormslowly 抱歉打扰 纯js问题解决了，但现在有个新的问题 demo：https://github.com/SamWeichangyue/test-mfsu.git . "@umijs/mfsu": "4.0.0-rc.23", 对文档里有个字段不是很理解 buildDepWithESBuild 我将demo 中的 buildDepWithESBuild改为 false; 然后会pnpm dev:mfsu 得到一个报错 ![image](https://user-images.githubusercontent.com/30724369/174207312-57af507f-e421-4273-b6cf-ce1147108409.png) 文档中这个字段是控制是否开启esbuild,
> > 
> > * 当buildDepWithESBuild 为true 并且 loader 为esbuildloader 才为真正的开启esbuild
> > * 那buildDepWithESBuild 为true ，loader还使用babel-loader 是走 babel-loader
> > * 那buildDepWithESBuild 为 false 时？会得到一个报错
> 
> 那buildDepWithESBuild 为 false 时？会得到一个报错
> 
> 这个你看下 上个回复exmaple 链接，msfu setWebpackConfig 需要一个 depConfig 的字段
> 
> 另外两个我确认下

其实就是最后一个问题，我只是列了下可能性，前两个确认没问题了，就最后一个，烦请确认下

**Comment by RainyLiao** [comment]
depConfig中需要配置什么，具有什么作用？

**Comment by stormslowly** [comment]
参考  [https://github.com/umijs/umi-next/blob/c986bc7c46703f416021e7fe5c85aaacb1fd3e09/examples/mfsu-independent/webpack.config.js#L92](https://github.com/umijs/umi-next/blob/c986bc7c46703f416021e7fe5c85aaacb1fd3e09/examples/mfsu-independent/webpack.config.js#L92)

**Comment by stormslowly** [comment]
> depConfig中需要配置什么，具有什么作用？

具体作用的话就是 配置依赖部分的代码如何打包编译。这个配置基本给简单的配置，不报错就行了，因为 umi 已经提供大部分场景下可以用的默认配置了。
