### ISSUE TITLE
typings.d.ts import 'umi/typings' not found!

### ISSUE THREAD

**Issue by unrealsmart** [umijs/umi-next#867]
![image](https://user-images.githubusercontent.com/11688458/172820519-b6e1dbe9-2023-4eeb-abed-15638e012cb8.png)

无法定位到 `umi/typings` 文件！
且导致 `*.less`, `*.jpg` 等文件的引用报错

**Comment by xierenyuan** [comment]
这里是别名引用, 真正的文件在临时文件中, 方便提供下 复现的demo 吗。

**Comment by unrealsmart** [comment]
@xierenyuan 基于`umi v4.0-rc.21`的测试项目，无任何改动。如您所述，`.umi`目录下没有生成`typings.ts`文件。

升级到`umi v4.0-rc.22`后问题解决，`.umi`目录下可以正常生成`typing.ts`文件。
感谢你的关注！
