### ISSUE TITLE
配置文件配置qiankun, model, dva, initialState，使用umi lint提交检查，提交不成功

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi-next#879]
umi lint提交错误提示：
umi lint:
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: qiankun, model, dva, initialState

版本：umijs/max@4.0.0-rc.22

**Comment by fz6m** [comment]
duplicated #855

**Comment by liangskyli** [comment]
使用max lint:报错：@babel/eslint-parser这个安装了，在@umijs/lint/node_modules下
```
Error: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.js » /Users/******/node_modules/@umijs/max/eslint.js': Cannot find module '@babel/eslint-parser'
```
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/31531283/173164772-26c8f539-5b70-4de1-a7f7-8e2b2d7a1029.png">
