### ISSUE TITLE
根据官网文档描述在子系统的src/app.ts中导出生命周期钩子无效

### ISSUE THREAD

**Issue by dashaowang** [umijs/umi-next#899]
在子系统中导出乾坤生命周期钩子，解析时无法正确加载，报错You need to export lifecycle functions in xxx entry
![image](https://user-images.githubusercontent.com/40166750/173728316-078c533e-ae35-46ce-8e1d-681093113fa8.png)

主系统qiankun插件版本：@umijs/plugin-qiankun@2.37.2
子系统umi版本：4.0.0-rc.22

**Comment by xierenyuan** [comment]
umi4 的微前端插件在 `@umijs/max` 中 具体文档看这里  https://next.umijs.org/docs/max/micro-frontend

**Comment by xierenyuan** [comment]
主系统是umi3 子系统是umi4 吗

**Comment by dashaowang** [comment]
> 主系统是umi3 子系统是umi4 吗

是的  大概知道原因了，应该是子系统没有引入qiankun插件，导致导出的生命周期钩子没有被暴露出去。
