### ISSUE TITLE
SSR errors

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi-next#922]
### `ERROR: Could not resolve "react"`

Step to reproduce:
1. `pnpx create-umi@next`
1. Pick `Simple App`
1. add `ssr: {}` into `.umirc.ts`
1. `pnpm run dev`

### `ERROR: [plugin: less-loader] '~antd/es/style/themes/index.less' wasn't found.`

Step to reproduce:
1. `pnpx create-umi@next`
1. Pick `Enterprise App`
1. add `ssr: {}` into `.umirc.ts`
1. `pnpm run dev`

**Comment by sorrycc** [comment]
> ERROR: Could not resolve "react"

pnpm i react react-dom -D

> ERROR: [plugin: less-loader] '~antd/es/style/themes/index.less' wasn't found.

pro 和 antd 的不支持 ssr，不要用这些依赖。
