### ISSUE TITLE
umi4  不能定义 html 模版了吗 

### ISSUE THREAD

**Issue by ClenLu** [umijs/umi-next#930]
文档里没有  html 模板的配置   按照 umi3  放在 pages/document.ejs  不生效

**Comment by iamxiyang** [comment]
document.ejs 这种用法被废弃了，可以通过api来操作html自己拼装。类似问题  #868

**Comment by sorrycc** [comment]
先参考 https://github.com/umijs/umi-next/issues/868#issuecomment-1151088426 吧，document.ejs 的方式还没想好，主要是考虑 ssr 的场景下 ejs 模板不太友好。
