### ISSUE TITLE
chainWebpack

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi-next#943]
chainWebpack这个配置分包不生效了吗
@sorrycc 
mf-dep____vendor.0552c24e.js:205328 Uncaught TypeError: Cannot read properties of undefined (reading '__reactAutoBindPairs')大佬知道一直报这个错误是什么问题吗

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
