### ISSUE TITLE
max dev 运行，编译成功，访问页面 js 404无法访问 920号bug，不知道如何再打开 ，现在重新登记

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi-next#949]
复现demo见里面的bug：https://github.com/umijs/umi-next/issues/920

**Comment by sorrycc** [comment]
1、js 404 问题不是解了吗？
2、「Loading CSS chunk 2 failed」的问题需要解的话，请给复现 DEMO

**Comment by liangskyli** [comment]
第一个问题：$('head').html 会出现404，不能直接替换head的内容吗？demo里有复现，第二个问题，我看下后面找时间如何复现

**Comment by sorrycc** [comment]
不能直接替换，替换了就缺少 umi 生成的一些关键元素了，用 append 的方式。
