### ISSUE TITLE
升级时 加载node_modules 异常 react-dev-inspector/plugins/umi/react-inspector, can not be resolved

### ISSUE THREAD

**Issue by qlandroid** [umijs/umi-next#953]
Error: Invalid plugin react-dev-inspector/plugins/umi/react-inspector, can not be resolved.

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
