### ISSUE TITLE
[BUG] fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: qiankun

### ISSUE THREAD

**Issue by textqaz** [umijs/umi-next#957]
.umirc
`export default {
  npmClient: 'yarn',
  qiankun: {
    master: {}
  }
};`
<img width="345" alt="image" src="https://user-images.githubusercontent.com/16917336/174946241-04342c85-f31b-46b3-9ad4-863e51d18de6.png">

package.json
`{
  "private": true,
  "scripts": {
    "dev": "umi dev",
    "build": "umi build",
    "postinstall": "umi setup",
    "start": "npm run dev"
  },
  "dependencies": {
    "@umijs/max": "^4.0.0",
    "umi": "^4.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "typescript": "^4.1.2"
  }
}
`
<img width="522" alt="image" src="https://user-images.githubusercontent.com/16917336/174946260-498968b8-2a11-4a3b-9e49-19c1ca26a0d3.png">

以上配置 执行yarn 安装依赖报错如下
![image](https://user-images.githubusercontent.com/16917336/174946160-2b74affe-f9df-444d-8fa9-e9d67f0c51e2.png)

**Comment by fz6m** [comment]
1. `@umijs/max` 是 `umi` 的升级版，不需要同时安装 `umi` 和 `@umijs/max` 。

2. 使用 `@umijs/max` 时，所有 scripts 命令请使用 `max [command]` 代替 `umi [command]` ，因为 `@umijs/max` 才默认包含了 `qiankun` 的功能。
