### ISSUE TITLE
qiankun 主应用配置fetch时，加载子应用404 (Not Found)

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi-next#962]
问题：qiankun 主应用配置fetch时，加载子应用404 (Not Found)
```
app.ts:22          GET http://localhost:8010/slave 404 (Not Found)

Uncaught (in promise) Error: [qiankun]: You need to export lifecycle functions in qiankun-app entry
```
qiankun 主应用配置fetch注释后，加载子应用正常

复现demo: https://github.com/liangskyli/umi4-qiankun-strictStyleIsolation-bug
操作步骤见README.md

**Comment by fz6m** [comment]
See #853 

请明确指明 fetch 请求的 `accept` 类型

**Comment by liangskyli** [comment]
umi3使用正常，类型又不能固定指定，不同类型都存在，应该要处理下





------------------ 原始邮件 ------------------
发件人: Yingci ***@***.***&gt;
发送时间: 2022年6月23日 08:04
收件人: umijs/umi-next ***@***.***&gt;
抄送: liangsky ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [umijs/umi-next] qiankun 主应用配置fetch时，加载子应用404 (Not Found) (Issue #962)

**Comment by sorrycc** [comment]
这是 umi 4 dev 阶段加的限制，请参考 https://github.com/umijs/umi-next/issues/853#issuecomment-1147337913 解。

**Comment by liangskyli** [comment]
@sorrycc  那构建生产会有问题吗？需要区分吗？加headers: { 
     accept: 'text/html', 
   },  生产环境也可以加吗？
