### ISSUE TITLE
Unhandled Rejection (Error): register failed, invalid key getInitialState from plugin 

### ISSUE THREAD

**Issue by devinRex** [umijs/umi-next#970]
最小复现步骤：
1.  执行`npx create-umi`
2.  pick Simple App
3. 在src 目录下增加 app.ts 文件
`
export function getInitialState() {
  return {
    userName: '用户名',
    userId: '用户 ID',
  };
}
`

提示错误：
Unhandled Rejection (Error): register failed, invalid key getInitialState from plugin

**Comment by devinRex** [comment]
"umi": "^4.0.0"

**Comment by fz6m** [comment]
这是 max 自带的功能，请使用 `Ant Design Pro` 模板创建项目
